// libs/porrtal-components/a-quick-start-demo/src/lib/esri/digital-elevation/digital-elevation-map/digital-elevation-map.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-digital-elevation-map',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './digital-elevation-map.component.html',
  styleUrls: ['./digital-elevation-map.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DigitalElevationMapComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>digital-elevation-map works!</p>

// libs/porrtal-components/r-quick-start-demo/src/lib/esri/digital-elevation/digital-elevation-map/digital-elevation-map.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './digital-elevation-map.module.scss';

/* eslint-disable-next-line */
export interface DigitalElevationMapProps {}

export function DigitalElevationMap(props: DigitalElevationMapProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to DigitalElevationMap!</h1>
    </div>
  );
}

export default DigitalElevationMap;
