// libs/porrtal-components/r-quick-start-demo/src/lib/hierarchy/zoomable-treemap/zoomable-treemap.tsx
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './zoomable-treemap.module.scss';

/* eslint-disable-next-line */
export interface ZoomableTreemapProps {}

export function ZoomableTreemap(props: ZoomableTreemapProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to ZoomableTreemap!</h1>
    </div>
  );
}

export default ZoomableTreemap;

// libs/porrtal-components/a-quick-start-demo/src/lib/hierarchy/zoomable-treemap/zoomable-treemap.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-zoomable-treemap',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './zoomable-treemap.component.html',
  styleUrls: ['./zoomable-treemap.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ZoomableTreemapComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>zoomable-treemap works!</p>
