// apps/n/porrtal-io-app/pages/react/inside-porrtal/index.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './index.module.scss';

/* eslint-disable-next-line */
export interface InsidePorrtalProps {}

export function InsidePorrtal(props: InsidePorrtalProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to InsidePorrtal!</h1>
    </div>
  );
}

export default InsidePorrtal;

// apps/a/porrtal-io-app/src/app/inside-porrtal/inside-porrtal.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'porrtal-workspace-inside-porrtal',
  templateUrl: './inside-porrtal.component.html',
  styleUrls: ['./inside-porrtal.component.scss'],
})
export class InsidePorrtalComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>inside-porrtal works!</p>
