// libs/porrtal/r-shell-material/src/lib/entity-menu/entity-menu.tsx
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Icon, Menu } from '@mui/material';
import {
  combineViewStateStateAndActionState,
  EntityMenuProps,
  replaceParameters,
  useShellDispatch,
  useShellState,
} from '@porrtal/r-shell';
import { IconMenuItem } from 'mui-nested-menu';
import { useState, MouseEvent } from 'react';
import { v4 as uuidv4 } from 'uuid';

export function EntityMenu(props: EntityMenuProps) {
  const shellState = useShellState();
  const dispatch = useShellDispatch();

  const [anchorEl, setAnchorEl] = useState<HTMLButtonElement | null>(null);

  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  const open = Boolean(anchorEl);

  if (
    shellState.views.filter((view) => view.entityType === props.entityType)
      .length > 1
  ) {
    return (
      <>
        <span
          id="entity-menu-trigger"
          aria-controls={open ? 'basic-menu' : undefined}
          aria-haspopup="true"
          aria-expanded={open ? 'true' : undefined}
          onClick={handleClick}
        >
          {props.children}
        </span>
        <Menu
          id="basic-menu"
          anchorEl={anchorEl}
          open={open}
          onClose={handleClose}
          MenuListProps={{
            'aria-labelledby': 'basic-button',
          }}
        >
          {shellState.views
            .filter((view) => view.entityType === props.entityType)
            .map((view) => {
              const newState = combineViewStateStateAndActionState(
                view.state,
                props.state
              );

              const newKey = replaceParameters(
                view.key ?? uuidv4(),
                newState ?? {}
              ).replaced;
              const newEntityMenuText = replaceParameters(
                view.entityTypeMenuText ?? view.displayText ?? '',
                newState ?? {}
              ).replaced;
              const newDisplayIcon = replaceParameters(
                view.displayIcon ?? '',
                newState ?? {}
              ).replaced;

              return (
                <IconMenuItem
                  key={newKey}
                  leftIcon={<Icon>{newDisplayIcon}</Icon>}
                  label={newEntityMenuText}
                  onClick={() => {
                    dispatch({
                      type: 'launchView',
                      viewId: view.viewId ?? view.componentName,
                      state: newState,
                    });
                    setAnchorEl(null);
                  }}
                />
              );
            })}
        </Menu>
      </>
    );
  } else if (
    shellState.views.filter((view) => view.entityType === props.entityType)
      .length === 1
  ) {
    const view = shellState.views.filter(
      (view) => view.entityType === props.entityType
    )[0];
    return (
      <span
        onClick={() => {
          const newState = combineViewStateStateAndActionState(
            view.state,
            props.state
          );
          dispatch({
            type: 'launchView',
            viewId: view.viewId ?? view.componentName,
            state: newState,
          });
        }}
      >
        {props.children}
      </span>
    );
  } else {
    return <>{props.children}</>;
  }
}

export default EntityMenu;

// libs/porrtal/a-shell-material/src/lib/entity-menu/entity-menu.component.ts
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  ChangeDetectionStrategy,
  Component,
  HostListener,
  Input,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatMenuModule, MatMenuTrigger } from '@angular/material/menu';
import { StateObject, View } from '@porrtal/a-api';
import { SearchStateService, ShellStateService } from '@porrtal/a-shell';
import { map, Observable } from 'rxjs';
import { MatIconModule } from '@angular/material/icon';
import { replaceParameters } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-entity-menu',
  standalone: true,
  imports: [CommonModule, MatMenuModule, MatIconModule],
  templateUrl: './entity-menu.component.html',
  styleUrls: ['./entity-menu.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EntityMenuComponent {
  _entityType?: string;
  @Input() set entityType(value: string | undefined) {
    this._entityType = value;
    this.createEntityViewObs();
  }
  get entityType() {
    return this._entityType;
  }

  _state?: StateObject;
  @Input() set state(value: StateObject | undefined) {
    this._state = value;
    this.createEntityViewObs();
  }
  get state() {
    return this._state;
  }

  public entityViews$?: Observable<View[]>;

  public menuPosition = {
    x: '0px',
    y: '0px',
  };

  @ViewChild(MatMenuTrigger, { static: true })
  menuTrigger!: MatMenuTrigger;

  constructor(
    private shellStateService: ShellStateService,
    private searchStateService: SearchStateService
  ) {
    this.createEntityViewObs();
  }

  @HostListener('click', ['$event'])
  containerClick(evt?: MouseEvent) {
    // alert(
    //   `entity type: ${this.entityType}\r\n` +
    //     `state: ${JSON.stringify(this.state, null, 2)}\r\n` +
    //     `mouseX: ${evt?.clientX}`
    // );

    this.menuPosition = {
      x: evt?.clientX ? `${evt?.clientX}px` : '0px',
      y: evt?.clientY ? `${evt?.clientY}px` : '0px',
    };

    this.menuTrigger.openMenu();
  }

  createEntityViewObs() {
    const entityType = this.entityType;
    const sss = this.shellStateService;
    this.entityViews$ = sss.select('views').pipe(
      map((vArr) => {
        if (!vArr || vArr.length < 1) {
          return [] as View[];
        }
        return [
          ...vArr
            .filter(
              (v) => v.entityType && entityType && v.entityType === entityType
            )
            .map((v) => ({
              ...v,
              displayText: this.state
                ? replaceParameters(v.displayText, this.state).replaced
                : v.displayText,
            })),
        ] as View[];
      })
    );
  }

  launchView(view: View, shiftKey: boolean) {
    if (view && view.viewId) {
      this.shellStateService.dispatch({
        type: 'launchView',
        viewId: view.viewId,
        state: this.state,
      });

      if (!shiftKey) {
        this.searchStateService.dispatch({
          type: 'closeSearchDialog',
        });
      }
    }
  }
}

<ng-container (click)="containerClick()">
  <ng-content></ng-content>
</ng-container>
<div
  [ngStyle]="{ position: 'fixed', top: menuPosition.y, left: menuPosition.x }"
  [matMenuTriggerFor]="menu"
></div>
<mat-menu #menu="matMenu" style="z-index: 99999 !important">
  <ng-template matMenuContent>
    <button
      mat-menu-item
      (click)="launchView(view, $event.shiftKey)"
      *ngFor="let view of entityViews$ | async"
    >
      <span class="menu-item-arrangement"
        ><mat-icon class="menu-item-icon">{{ view.displayIcon }}</mat-icon
        >{{ view.displayText }}</span
      >
    </button>
  </ng-template>
</mat-menu>
