// libs/porrtal/a-shell-material/src/lib/shell-state-dashboard/views-card/views-card.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, ElementRef, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShellStateService } from '@porrtal/a-shell';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatCardModule } from '@angular/material/card';
import { BehaviorSubject, Observable } from 'rxjs';
import { View } from '@porrtal/a-api';
import { MatTooltipModule } from '@angular/material/tooltip';

@Component({
  selector: 'porrtal-views-card',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatIconModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatTooltipModule
  ],
  templateUrl: './views-card.component.html',
  styleUrls: ['./views-card.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ViewsCardComponent {
  @Input() data?: any;
  
  isMaximized$ = new BehaviorSubject<boolean>(false);
  childIndex = -1;
  parentNativeEl: any;
  views$: Observable<View[]>;

  constructor(
    private readonly el: ElementRef,
    private shellStateService: ShellStateService
  ) {
    this.views$ = shellStateService.select('views');
  }

  toggleMax() {
    this.shellStateService.dispatch({
      type: 'maximize',
      htmlEl: this.el.nativeElement,
      maximizeText: 'auth n',
      restore: () => {
        this.isMaximized$.next(false);
        console.log('auth-n-card restore', this);
      },
    });

    this.isMaximized$.next(true);
  }
}

<mat-card class="container-container" [class.maximize]="isMaximized$ | async">
  <div class="container">
    <mat-toolbar class="toolbar" color="accent">
      <!-- key icon -->
      <span class="status-icon">
        <mat-icon>view_list</mat-icon>
      </span>

      <!-- card type -->
      <span class="card-type">views({{ (views$ | async)?.length }})</span>

      <!-- card maximize button -->
      <button
        *ngIf="!(isMaximized$ | async)"
        mat-button
        (click)="toggleMax()"
        class="maximize-button"
      >
        <mat-icon class="maximize-icon">north_east</mat-icon>
      </button>
    </mat-toolbar>

    <!-- card content -->
    <div class="card-content-container">
      <div *ngIf="views$ | async as views" class="properties-container">
        <!-- views -->
        <ng-container *ngFor="let view of views">
          <!-- launch at statup -->
          <mat-icon class="status-icon" *ngIf="view.launchAtStartup"
            >rocket_launch</mat-icon
          >
          <span *ngIf="!view.launchAtStartup"></span>

          <!-- permissions -->
          <mat-icon class="status-icon" *ngIf="view.permissions" [matTooltip]="view.permissions"
            >lock</mat-icon
          >
          <span *ngIf="!view.permissions"></span>

          <!-- entity type -->
          <mat-icon class="status-icon" *ngIf="view.entityType" [matTooltip]="view.entityType"
            >category</mat-icon
          >
          <span *ngIf="!view.entityType"></span>

          <!-- view id -->
          <span class="property-title">{{ view.viewId }}</span>

          <!-- pane type -->
          <span class="property-value">{{ view.paneType }}</span>
        </ng-container>
      </div>
    </div>
  </div>
</mat-card>

// libs/porrtal/r-shell-blueprint/src/lib/shell-state-dashboard/views-card/views-card.tsx
/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './views-card.module.scss';
import { CardContainerProps, useShellDispatch, useShellState } from '@porrtal/r-shell';
import { Icon } from '@blueprintjs/core';
import { Fragment, useRef, useState } from 'react';
import { Tooltip2 } from '@blueprintjs/popover2';

export function ViewsCard(props: CardContainerProps) {
  const shellState = useShellState();
  const shellDispatch = useShellDispatch();
  const cardRef = useRef<HTMLDivElement>(null);
  const [isMaximized, setIsMaximized] = useState(false);

  return (
    <div ref={cardRef} className={styles['card-layout']}>
      {!isMaximized && (
        <div className={styles['card-header']}>
          <span>views</span>
          <Icon
            icon="arrow-top-right"
            onClick={() => {
              if (cardRef.current) {
                shellDispatch({
                  type: 'maximize',
                  htmlEl: cardRef.current,
                  maximizeText: `auth z: ${
                    (props.card.data as { name: string }).name
                  }`,
                  restore: () => setIsMaximized(false),
                });
                setIsMaximized(true);
              }
            }}
          ></Icon>
        </div>
      )}
      <div className={styles['card-content-container']}>
        <div className={styles['views-container']}>
          {shellState.views.map((view) => (
            <Fragment key={view.viewId}>
              <span key="launchAtStartup">
                {view.launchAtStartup && <Icon icon="rocket-slant" />}
              </span>

              <span key="permissions">
                {view.permissions && (
                  <Tooltip2 content={view.permissions}>
                    <Icon icon="lock" />
                  </Tooltip2>
                )}
              </span>

              <span key="entityType">
                {view.entityType && (
                  <Tooltip2 content={view.entityType}>
                    <Icon icon="shapes" />
                  </Tooltip2>
                )}
              </span>

              <span key="viewId">{view.viewId}</span>
            </Fragment>
          ))}
        </div>
      </div>
    </div>
  );
}

export default ViewsCard;
