// libs/porrtal/r-shell-material/src/lib/view-stack/view-stack.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  CardHeader,
  Divider,
  Icon,
  Tab,
  Tabs,
  Tooltip,
} from '@mui/material';
import React, { Dispatch, useMemo, MouseEvent, useRef } from 'react';
import {
  ShellAction,
  useShellDispatch,
  ViewHost,
  ViewStackProps,
} from '@porrtal/r-shell';
import styles from './view-stack.module.scss';
import { NestedMenuItem, IconMenuItem } from 'mui-nested-menu';
import { ContextMenu } from '../context-menu/ContextMenu';
import {
  paneArrangements,
  PaneType,
  paneTypes,
  ViewState,
} from '@porrtal/r-api';
import { v4 as uuidv4 } from 'uuid';
import { MenuItemData } from 'mui-nested-menu';

export function ViewStack(props: ViewStackProps) {
  const dispatch = useShellDispatch();
  const currentIndex = useMemo(() => {
    for (let ii = 0; ii < props.pane.viewStates.length; ii++) {
      if (props.pane.viewStates[ii].key === props.pane.currentKey) {
        return ii;
      }
    }
    return -1;
  }, [props.pane]);

  const handleChange = (event: React.SyntheticEvent, newIndex: number) => {
    dispatch({
      type: 'setCurrentViewStateByKey',
      key: props.pane.viewStates[newIndex].key,
      pane: props.pane,
    });
  };

  switch (props.pane.arrange) {
    case 'tabs-top':
      return (
        <ViewStackTabsTop
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          currentIndex={currentIndex}
          dispatch={dispatch}
          handleChange={handleChange}
          onClose={props.onClose}
        />
      );

    case 'tabs-left':
      return (
        <ViewStackTabsLeft
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          currentIndex={currentIndex}
          dispatch={dispatch}
          handleChange={handleChange}
        />
      );

    case 'cards':
      return (
        <ViewStackCards
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          currentIndex={currentIndex}
          dispatch={dispatch}
          handleChange={handleChange}
        />
      );
  }

  return (
    <div>ViewStack Arrangement ('{props.pane.arrange}') Not Supported.</div>
  );
}

function ViewStackTabsTop(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    currentIndex: number;
    handleChange: (event: React.SyntheticEvent, newIndex: number) => void;
  }
) {
  const viewHostRef = useRef<(HTMLDivElement | null)[]>([]);

  return (
    <div className={`${styles['container']} ${styles[props.pane.arrange]}`}>
      <Box
        sx={{
          borderBottom: 1,
          borderColor: 'divider',
          backgroundColor: 'gainsboro',
        }}
      >
        <Tabs
          value={props.currentIndex}
          variant="scrollable"
          scrollButtons="auto"
          onChange={props.handleChange}
          className={styles['tabs']}
        >
          {props.pane.viewStates.map((item, index) => (
            <Tab
              key={item.key}
              label={
                <ViewStackContextMenu
                  pane={props.pane}
                  showUserInfo={props.showUserInfo}
                  showDevInfo={props.showDevInfo}
                  dispatch={props.dispatch}
                  item={item}
                  viewHostElements={viewHostRef.current}
                  viewHostElementIndex={index}
                ></ViewStackContextMenu>
              }
            ></Tab>
          ))}
          {props.onClose && (
            <Button
              className={styles['view-stack-close-button']}
              onClick={(evt) => (props.onClose ? props.onClose(evt) : null)}
            >
              <Icon>clear</Icon>
              <span>close</span>
            </Button>
          )}
        </Tabs>
      </Box>
      <div className={styles['view-host-container']}>
        {props.pane.viewStates.map((item, index) => (
          <div
            ref={(element) => {
              viewHostRef.current[index] = element;
            }}
            key={item.key}
          >
            <ViewHost
              key={item.key}
              viewState={item}
              zIndex={index === props.currentIndex ? 10 : 0}
            ></ViewHost>
          </div>
        ))}
        <div
          style={{
            zIndex: 5,
            backgroundColor: 'white',
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
          }}
        ></div>
      </div>
    </div>
  );
}

function ViewStackTabsLeft(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    currentIndex: number;
    handleChange: (event: React.SyntheticEvent, newIndex: number) => void;
  }
) {
  const viewHostRef = useRef<(HTMLDivElement | null)[]>([]);

  return (
    <div className={`${styles['container']} ${styles[props.pane.arrange]}`}>
      <Box
        sx={{
          borderBottom: 1,
          borderColor: 'divider',
          backgroundColor: 'gainsboro',
        }}
      >
        <Tabs
          value={props.currentIndex}
          variant="scrollable"
          scrollButtons="auto"
          onChange={props.handleChange}
          className={styles['tabs']}
          orientation="vertical"
        >
          {props.pane.viewStates.map((item, index) => (
            <Tab
              key={item.key}
              iconPosition="start"
              label={
                <ViewStackContextMenu
                  pane={props.pane}
                  showUserInfo={props.showUserInfo}
                  showDevInfo={props.showDevInfo}
                  dispatch={props.dispatch}
                  item={item}
                  viewHostElements={viewHostRef.current}
                  viewHostElementIndex={index}
                ></ViewStackContextMenu>
              }
            ></Tab>
          ))}
        </Tabs>
      </Box>
      <div className={styles['view-host-container']}>
        {props.pane.viewStates.map((item, index) => (
          <div
            ref={(element) => {
              viewHostRef.current[index] = element;
            }}
            key={item.key}
          >
            <ViewHost
              key={item.key}
              viewState={item}
              zIndex={index === props.currentIndex ? 10 : 0}
            ></ViewHost>
          </div>
        ))}
        <div
          key="ind"
          style={{
            zIndex: 5,
            backgroundColor: 'white',
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
          }}
        ></div>
      </div>
    </div>
  );
}

function ViewStackCards(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    currentIndex: number;
    handleChange: (event: React.SyntheticEvent, newIndex: number) => void;
  }
) {
  const viewHostRef = useRef<(HTMLDivElement | null)[]>([]);

  return (
    <div className={styles['card-container']}>
      <div className={styles['cards']}>
        {props.pane.viewStates.map((item, index) => (
          <Card id={item.key} key={item.key} className={`${styles['card']}`}>
            <CardHeader
              sx={{
                padding: 0,
                backgroundColor:
                  index === props.currentIndex ? 'gainsboro' : '',
              }}
              title={
                <Button
                  onClick={(evt) => {
                    props.handleChange(evt, index);
                  }}
                >
                  <ViewStackContextMenu
                    pane={props.pane}
                    showUserInfo={props.showUserInfo}
                    showDevInfo={props.showDevInfo}
                    dispatch={props.dispatch}
                    item={item}
                    viewHostElements={viewHostRef.current}
                    viewHostElementIndex={index}
                    ></ViewStackContextMenu>
                </Button>
              }
            ></CardHeader>
            <CardContent sx={{ position: 'relative' }}>
              <div
                ref={(element) => {
                  viewHostRef.current[index] = element;
                }}
                className={styles['viewHostContainer']}
              >
                <ViewHost key={item.key} viewState={item}></ViewHost>
              </div>
            </CardContent>
            <CardActions></CardActions>
          </Card>
        ))}
      </div>
    </div>
  );
}

export default ViewStack;

function ViewStackContextMenu(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    viewHostElements: (HTMLDivElement | null)[];
    viewHostElementIndex: number;
  } & {
    item: ViewState;
  }
) {
  const moveIcons: { [key in PaneType]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  const menuItemsData: MenuItemData[] = [
    {
      uid: 'maximize-tab',
      label: 'maximize tab',
      leftIcon: <Icon>north_east</Icon>,
      callback: () => {
        const htmlEl = props.viewHostElements[props.viewHostElementIndex];
        if (htmlEl) {
          props.dispatch({
            type: 'maximize',
            htmlEl,
            maximizeText: `${props.item.displayText}`,
          });
        }
      },
    },
    ...(props.pane.paneType !== 'search'
      ? [
          {
            uid: 'close-tab',
            label: 'close tab',
            leftIcon: <Icon>clear</Icon>,
            callback: () => {
              props.dispatch({ type: 'deleteViewState', key: props.item.key });
            },
          },
        ]
      : []),
    ...(props.showUserInfo &&
    props.item.userInfo &&
    props.item.userInfo.length > 0
      ? [
          ...props.item.userInfo.map((info) => ({
            uid: `info ${info.viewId}`,
            label: info.state
              ? (info.state['displayText'] as string)
              : 'user help',
            leftIcon: (
              <Icon className="material-icons-outlined">
                ,{info.state ? (info.state['displayIcon'] as string) : 'help'}
              </Icon>
            ),
            callback: () =>
              props.dispatch({
                type: 'launchView',
                viewId: info.viewId,
                state: info.state,
              }),
          })),
        ]
      : []),
    ...(props.showDevInfo && props.item.devInfo && props.item.devInfo.length > 0
      ? [
          ...props.item.devInfo.map((info) => ({
            uid: `info ${info.viewId}`,
            label: info.state
              ? (info.state['displayText'] as string)
              : 'dev help',
            leftIcon: (
              <Icon className="material-icons-outlined">
                ,{info.state ? (info.state['displayIcon'] as string) : 'build'}
              </Icon>
            ),
            callback: () =>
              props.dispatch({
                type: 'launchView',
                viewId: info.viewId,
                state: info.state,
              }),
          })),
        ]
      : []),
    {
      uid: 'Arrange...',
      label: 'Arrange...',
      leftIcon: <Icon>pivot_table_chart</Icon>,
      items: [
        ...paneArrangements.map((paneArrangement) => ({
          uid: paneArrangement,
          label: paneArrangement,
          leftIcon: (
            <Icon className="material-icons-outlined">
              {props.pane.arrange === paneArrangement ? 'done' : ''}
            </Icon>
          ),
          callback: () =>
            props.dispatch({
              type: 'arrangePane',
              pane: props.pane,
              paneArrangement,
            }),
        })),
      ],
    },
    ...(props.pane.paneType !== 'search'
      ? [
          {
            uid: 'Move to...',
            label: 'Move to...',
            leftIcon: <Icon>open_with</Icon>,
            items: [
              ...paneTypes
                .filter(
                  (paneType) =>
                    paneType !== 'search' && paneType !== props.pane.paneType
                )
                .map((paneType) => ({
                  uid: `${paneType} pane`,
                  label: `${paneType} pane`,
                  leftIcon: (
                    <Icon className="material-icons-outlined">
                      {moveIcons[paneType]}
                    </Icon>
                  ),
                  callback: () =>
                    props.dispatch({
                      type: 'moveView',
                      key: props.item.key,
                      toPane: paneType,
                    }),
                })),
            ],
          },
        ]
      : []),
    {
      uid: 'Copy link',
      label: 'Copy link',
      leftIcon: <Icon>content_copy</Icon>,
      callback: () =>
        props.dispatch({
          type: 'copyToClipboard',
          viewState: props.item,
        }),
    },
  ];

  return (
    <ContextMenu menuItemsData={menuItemsData}>
      {props.pane.arrange !== 'tabs-left' && (
        <div>
          <Icon style={{ position: 'relative', top: '5px' }}>
            {props.item.displayIcon}
          </Icon>
          &nbsp;
          <Icon
            onClick={() => {
              const htmlEl = props.viewHostElements[props.viewHostElementIndex];
              if (htmlEl) {
                console.log('maximize...');
                props.dispatch({
                  type: 'maximize',
                  htmlEl,
                  maximizeText: `${props.item.displayText}`,
                });
              } else {
                console.log('maximize failure: no view host element...');
              }
            }}
            style={{ position: 'relative', top: '5px' }}
          >
            north_east
          </Icon>
          &nbsp;
          {props.item.displayText}&nbsp;
          {props.pane.paneType !== 'search' && (
            <Icon
              style={{ position: 'relative', top: '5px' }}
              onClick={(evt) =>
                props.dispatch({ type: 'deleteViewState', key: props.item.key })
              }
            >
              clear
            </Icon>
          )}
        </div>
      )}
      {props.pane.arrange === 'tabs-left' && props.pane.paneType === 'nav' && (
        <div>
          <Tooltip title={props.item.displayText} placement="right">
            <Icon
              style={{ position: 'relative', top: '3px', fontSize: '2rem' }}
              onClick={(evt) => {
                props.dispatch({
                  type: 'toggleNav',
                  item: props.item,
                });
              }}
            >
              {props.item.displayIcon}
            </Icon>
          </Tooltip>
        </div>
      )}
      {props.pane.arrange === 'tabs-left' && props.pane.paneType !== 'nav' && (
        <div>
          <Tooltip title={props.item.displayText} placement="right">
            <Icon
              style={{ position: 'relative', top: '3px', fontSize: '2rem' }}
            >
              {props.item.displayIcon}
            </Icon>
          </Tooltip>
        </div>
      )}
    </ContextMenu>
  );
}

// libs/porrtal/a-shell-material/src/lib/view-stack/view-stack.component.ts
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  QueryList,
  ViewChild,
  ViewChildren,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Pane,
  paneTypes,
  paneArrangements,
  ViewState,
  PaneType,
  PaneArrangement,
  ViewLaunch,
} from '@porrtal/a-api';
import { MatTabsModule } from '@angular/material/tabs';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule, MatMenuTrigger } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { MatListModule } from '@angular/material/list';
import { MatCardModule } from '@angular/material/card';
import { ShellStateService, ViewHostComponent } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-view-stack',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatIconModule,
    MatMenuModule,
    MatDividerModule,
    MatListModule,
    MatCardModule,
    ViewHostComponent,
  ],
  templateUrl: './view-stack.component.html',
  styleUrls: ['./view-stack.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ViewStackComponent implements AfterContentChecked {
  _pane?: Pane;
  @Input() set pane(value: Pane | undefined) {
    this._pane = value;
    this.paneTypes = paneTypes.filter(
      (pt) => pt !== 'search' && pt !== (this._pane?.paneType ?? '')
    );
    const ii = this.pane?.viewStates.findIndex(
      (vs) => vs.key === this.pane?.currentKey
    );
    if (ii !== undefined) {
      this.selectedTabIndex = ii;
    }
  }
  get pane() {
    return this._pane;
  }

  @ViewChild(MatMenuTrigger, { static: true }) matMenuTrigger?: MatMenuTrigger;
  @ViewChildren('card', { read: ElementRef }) cards?: QueryList<
    ElementRef<HTMLElement>
  >;

  @ViewChildren(ViewHostComponent)
  portalViewHosts?: QueryList<ViewHostComponent>;

  public paneTypes?: string[];
  public selectedTabIndex?: number;
  public paneArrangements = paneArrangements;
  menuTopLeftPosition = { x: '0', y: '0' };
  public moveIcons: { [key: string]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  constructor(public shellStateService: ShellStateService) {
    const ii = this.pane?.viewStates.findIndex(
      (vs) => vs.key === this.pane?.currentKey
    );
  }

  ngAfterContentChecked(): void {
    if (this.cards && this.pane) {
      this.cards.some((card, ii) => {
        const isSelected =
          this.pane?.currentKey === this.pane?.viewStates[ii].key;
        if (isSelected) {
          card.nativeElement.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
          });
        }
        return isSelected;
      });
    }
  }

  doChangeTabIndex(ii: number) {
    if (this.pane) {
      this.shellStateService.dispatch({
        type: 'setCurrentViewStateByKey',
        key: this.pane.viewStates[ii].key,
        pane: this.pane,
      });
    }
  }

  doContextMenu(evt: MouseEvent, viewState: ViewState, ii: number): void {
    evt.preventDefault();
    evt.stopPropagation();

    // we record the mouse position in our object
    this.menuTopLeftPosition.x = evt.clientX + 'px';
    this.menuTopLeftPosition.y = evt.clientY + 'px';

    if (this.matMenuTrigger) {
      this.matMenuTrigger.menuData = { viewState, ii };
      this.matMenuTrigger.openMenu();
    }
  }

  doCloseTab(evt: MouseEvent, viewState: ViewState): void {
    this.shellStateService.dispatch({
      type: 'deleteViewState',
      key: viewState.key,
    });
  }

  doMoveTab(evt: MouseEvent, viewState: ViewState, toPaneType: string): void {
    this.shellStateService.dispatch({
      type: 'moveView',
      key: viewState.key,
      toPane: toPaneType as PaneType,
    });
  }

  doSetArrangementType(
    evt: MouseEvent,
    viewState: ViewState,
    paneArrangement: PaneArrangement
  ): void {
    if (this.pane) {
      this.shellStateService.dispatch({
        type: 'arrangePane',
        pane: this.pane,
        paneArrangement,
      });
    }
  }

  doLaunch(viewLaunch: ViewLaunch) {
    console.log('launch info', viewLaunch);
    this.shellStateService.dispatch({
      type: 'launchView',
      viewId: viewLaunch.viewId,
      state: viewLaunch.state,
    });
  }

  doMaximizeTab(evt: MouseEvent, viewState: ViewState, ii: number) {
    this.portalViewHosts?.toArray()[ii].maximize();
  }
}

<ng-container [ngSwitch]="pane?.arrange ?? 'tabs-top'">
  <!-- tabs-top -->
  <mat-tab-group
    mat-stretch-tabs="false"
    mat-align-tabs="start"
    preserveContent
    *ngSwitchCase="'tabs-top'"
    (selectedIndexChange)="doChangeTabIndex($event)"
    [selectedIndex]="selectedTabIndex"
  >
    <mat-tab *ngFor="let viewState of pane?.viewStates; let ii = index">
      <ng-template mat-tab-label>
        <mat-icon
          (contextmenu)="doContextMenu($event, viewState, ii)"
          class="tab-icon"
          >{{ viewState.displayIcon }}</mat-icon
        >
        <mat-icon
          (contextmenu)="doContextMenu($event, viewState, ii)"
          (click)="doMaximizeTab($event, viewState, ii)"
          class="tab-icon"
          >north_east</mat-icon
        >
        <span (contextmenu)="doContextMenu($event, viewState, ii)">{{
          viewState.displayText
        }}</span>
        <mat-icon
          (click)="doCloseTab($event, viewState)"
          inline="true"
          class="close-icon"
          >close</mat-icon
        >
      </ng-template>
      <porrtal-view-host
        #porrtalViewHost
        [viewState]="viewState"
      ></porrtal-view-host>
    </mat-tab>
  </mat-tab-group>

  <!-- tabs-left -->
  <div class="vertical-tabs-container" *ngSwitchCase="'tabs-left'">
    <div class="vertical-tabs-tabs-container">
      <div class="vertical-tabs-nav-list">
        <mat-nav-list>
          <mat-list-item
            *ngFor="let viewState of pane?.viewStates; let ii = index"
            [ngClass]="{ selected: viewState.key === pane?.currentKey }"
            (click)="doChangeTabIndex(ii)"
            (contextmenu)="doContextMenu($event, viewState, ii)"
          >
            <a
              *ngIf="pane?.paneType === 'nav'"
              tabindex="0"
              class="vertical-tabs-anchor"
              (click)="
                shellStateService.dispatch({
                  type: 'toggleNav',
                  item: viewState
                })
              "
            >
              <div>
                <mat-icon>{{ viewState.displayIcon }}</mat-icon>
              </div>
            </a>
            <a
              *ngIf="pane?.paneType !== 'nav'"
              tabindex="0"
              class="vertical-tabs-anchor"
            >
              <div>
                <mat-icon>{{ viewState.displayIcon }}</mat-icon>
              </div>
            </a>
          </mat-list-item>
        </mat-nav-list>
      </div>
    </div>
    <div class="vertical-tabs-content">
      <div style="position: relative; height: 100%">
        <div
          class="vertical-tabs-view-host-container"
          *ngFor="let viewState of pane?.viewStates; let ii = index"
          [style.zIndex]="viewState.key === pane?.currentKey ? 10 : 0"
        >
          <porrtal-view-host
            #porrtalViewHost
            [viewState]="viewState"
          ></porrtal-view-host>
        </div>
        <div class="vertical-tabs-content-background-div"></div>
      </div>
    </div>
  </div>

  <!-- cards -->
  <div *ngSwitchCase="'cards'" class="card-container">
    <div class="cards">
      <mat-card
        #card
        *ngFor="let viewState of pane?.viewStates; let ii = index"
        class="card"
      >
        <mat-card-title style="margin: 0">
          <div
            class="card-title"
            [ngClass]="{
              'selected-card-title': viewState.key === pane?.currentKey
            }"
            (click)="doChangeTabIndex(ii)"
            (contextmenu)="doContextMenu($event, viewState, ii)"
          >
            <mat-icon class="tab-icon">{{ viewState.displayIcon }}</mat-icon>
            <mat-icon
              (click)="doMaximizeTab($event, viewState, ii)"
              class="tab-icon"
              >north_east</mat-icon
            >
            <span>{{ viewState.displayText }}</span>
            <mat-icon
              (click)="doCloseTab($event, viewState)"
              inline="true"
              class="close-icon"
              >close</mat-icon
            >
          </div>
        </mat-card-title>
        <mat-card-content>
          <div class="view-host-container">
            <porrtal-view-host
              #porrtalViewHost
              [viewState]="viewState"
            ></porrtal-view-host>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</ng-container>

<!-- an hidden div is created to set the position of appearance of the menu-->
<div
  style="visibility: hidden; position: fixed"
  [style.left]="menuTopLeftPosition.x"
  [style.top]="menuTopLeftPosition.y"
  [matMenuTriggerFor]="rightMenu"
></div>

<!-- standard material menu -->
<mat-menu #rightMenu="matMenu">
  <ng-template matMenuContent let-viewState="viewState" let-ii="ii">
    <button mat-menu-item (click)="doMaximizeTab($event, viewState, ii)">
      <span>
        <mat-icon inline="true" class="menu-close-icon">north_east</mat-icon>
        <span>Maximize Tab</span>
      </span>
    </button>
    <mat-divider></mat-divider>
    <button mat-menu-item (click)="doCloseTab($event, viewState)">
      <span>
        <mat-icon inline="true" class="menu-close-icon">close</mat-icon>
        <span>Close Tab</span>
      </span>
    </button>
    <mat-divider></mat-divider>
    <button
      *ngIf="
        viewState?.userInfo &&
          viewState?.userInfo.length > 0 &&
          shellStateService.select('showUserInfo') | async
      "
      mat-menu-item
      [matMenuTriggerFor]="info"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon material-icons-outlined"
          >info</mat-icon
        >
        <span>Info...</span>
      </span>
    </button>
    <button
      *ngIf="
        viewState?.devInfo &&
          viewState?.devInfo.length > 0 &&
          shellStateService.select('showDevInfo') | async
      "
      mat-menu-item
      [matMenuTriggerFor]="devInfo"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon material-icons-outlined"
          >build</mat-icon
        >
        <span>Dev Info...</span>
      </span>
    </button>
    <button
      mat-menu-item
      class="menu-button"
      [matMenuTriggerFor]="arrangeOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon"
          >pivot_table_chart</mat-icon
        >
        <span>Arrange...</span>
      </span>
    </button>
    <button
      mat-menu-item
      [matMenuTriggerFor]="moveOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">open_with</mat-icon>
        <span>Move To...</span>
      </span>
    </button>
    <button
      mat-menu-item
      (click)="
        shellStateService.dispatch({
          type: 'copyToClipboard',
          viewState: this.viewState
        })
      "
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">content_copy</mat-icon>
        <span>Copy link</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #info="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doLaunch(viewLaunch)"
      mat-menu-item
      *ngFor="let viewLaunch of viewState.userInfo"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-close-icon material-icons-outlined"
          >{{ viewLaunch.state['displayIcon'] }}</mat-icon
        >
        <span>{{ viewLaunch.state['displayText'] }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #devInfo="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doLaunch(viewLaunch)"
      mat-menu-item
      *ngFor="let viewLaunch of viewState.devInfo"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-close-icon material-icons-outlined"
          >{{ viewLaunch.state['displayIcon'] }}</mat-icon
        >
        <span>{{ viewLaunch.state['displayText'] }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #arrangeOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      mat-menu-item
      (click)="doSetArrangementType($event, viewState, paneArrangement)"
      *ngFor="let paneArrangement of paneArrangements"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">{{
          pane?.arrange === paneArrangement ? 'done' : ''
        }}</mat-icon>
        <span>{{ paneArrangement }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #moveOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doMoveTab($event, viewState, paneType)"
      mat-menu-item
      *ngFor="let paneType of paneTypes"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-move-to-icon material-icons-outlined"
          >{{ moveIcons[paneType] }}</mat-icon
        >
        <span>{{ paneType }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>
