// libs/porrtal-components/a-quick-start-material/src/lib/account/account-create/account-create.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-account-create',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './account-create.component.html',
  styleUrls: ['./account-create.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccountCreateComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// libs/porrtal-components/r-quick-start-blueprint/src/lib/account/account-create/account-create.tsx
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './account-create.module.scss';

/* eslint-disable-next-line */
export interface AccountCreateProps {}

export function AccountCreate(props: AccountCreateProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to AccountCreate!</h1>
    </div>
  );
}

export default AccountCreate;
