// libs/porrtal/a/shell-material/src/lib/view-stack/view-stack.component.ts
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  QueryList,
  ViewChild,
  ViewChildren,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Pane,
  paneTypes,
  paneArrangements,
  ViewState,
  PaneType,
  PaneArrangement,
} from '@porrtal/a-api';
import { MatTabsModule } from '@angular/material/tabs';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule, MatMenuTrigger } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { MatListModule } from '@angular/material/list';
import { MatCard, MatCardModule } from '@angular/material/card'
import { ShellStateService, ViewHostComponent } from '@porrtal/a-shell';
import { ViewLaunch } from 'libs/porrtal/a/api/src/lib/view-launch';

@Component({
  selector: 'porrtal-view-stack',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatIconModule,
    MatMenuModule,
    MatDividerModule,
    MatListModule,
    MatCardModule,
    ViewHostComponent,
  ],
  templateUrl: './view-stack.component.html',
  styleUrls: ['./view-stack.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ViewStackComponent implements AfterContentChecked {
  _pane?: Pane;
  @Input() set pane(value: Pane | undefined) {
    this._pane = value;
    this.paneTypes = paneTypes.filter(
      (pt) => pt !== 'search' && pt !== (this._pane?.paneType ?? '')
    );
    const ii = this.pane?.viewStates.findIndex(vs => vs.key === this.pane?.currentKey);
    if (ii !== undefined) {
      this.selectedTabIndex = ii;
    }
  }
  get pane() {
    return this._pane;
  }

  @ViewChild(MatMenuTrigger, { static: true }) matMenuTrigger?: MatMenuTrigger;
  @ViewChildren('card', { read: ElementRef<HTMLElement>}) cards?: QueryList<ElementRef<HTMLElement>>;

  public paneTypes?: string[];
  public selectedTabIndex?: number;
  public paneArrangements = paneArrangements;
  menuTopLeftPosition = { x: '0', y: '0' };
  public moveIcons: { [key: string]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  constructor(public shellStateService: ShellStateService) {
    const ii = this.pane?.viewStates.findIndex(vs => vs.key === this.pane?.currentKey)
  }

  ngAfterContentChecked(): void {
    if (this.cards && this.pane) {
      this.cards.some((card, ii) => {
        const isSelected = this.pane?.currentKey === this.pane?.viewStates[ii].key
        if (isSelected) {
          card.nativeElement.scrollIntoView({ behavior: 'smooth', block: 'start'});
        }
        return isSelected;
      })
    }
  }

  doChangeTabIndex(ii: number) {
    if (this.pane) {
      this.shellStateService.dispatch({
        type: 'setCurrentViewStateByKey',
        key: this.pane.viewStates[ii].key,
        pane: this.pane,
      });
    }
  }

  doContextMenu(evt: MouseEvent, viewState: ViewState): void {
    evt.preventDefault();
    evt.stopPropagation();

    // we record the mouse position in our object
    this.menuTopLeftPosition.x = evt.clientX + 'px';
    this.menuTopLeftPosition.y = evt.clientY + 'px';

    if (this.matMenuTrigger) {
      this.matMenuTrigger.menuData = { viewState };
      this.matMenuTrigger.openMenu();
    }
  }

  doCloseTab(evt: MouseEvent, viewState: ViewState): void {
    this.shellStateService.dispatch({
      type: 'deleteViewState',
      key: viewState.key,
    });
  }

  doMoveTab(evt: MouseEvent, viewState: ViewState, toPaneType: string): void {
    this.shellStateService.dispatch({
      type: 'moveView',
      key: viewState.key,
      toPane: toPaneType as PaneType,
    });
  }

  doSetArrangementType(
    evt: MouseEvent,
    viewState: ViewState,
    paneArrangement: PaneArrangement
  ): void {
    if (this.pane) {
      this.shellStateService.dispatch({
        type: 'arrangePane',
        pane: this.pane,
        paneArrangement,
      });
    }
  }

  doLaunch(viewLaunch: ViewLaunch) {
    console.log('launch info', viewLaunch);
    this.shellStateService.dispatch({
      type: 'launchView',
      viewId: viewLaunch.viewId,
      state: viewLaunch.state
    })
  }
}

<ng-container [ngSwitch]="pane?.arrange ?? 'tabs-top'">
  <!-- tabs-top -->
  <mat-tab-group
    preserveContent
    *ngSwitchCase="'tabs-top'"
    (selectedIndexChange)="doChangeTabIndex($event)"
    [selectedIndex]="selectedTabIndex"
  >
    <mat-tab *ngFor="let viewState of pane?.viewStates">
      <ng-template mat-tab-label>
        <mat-icon
          (contextmenu)="doContextMenu($event, viewState)"
          class="tab-icon"
          >{{ viewState.displayIcon }}</mat-icon
        >
        <span (contextmenu)="doContextMenu($event, viewState)">{{
          viewState.displayText
        }}</span>
        <mat-icon
          (click)="doCloseTab($event, viewState)"
          inline="true"
          class="close-icon"
          >close</mat-icon
        >
      </ng-template>
      <porrtal-view-host [viewState]="viewState"></porrtal-view-host>
    </mat-tab>
  </mat-tab-group>

  <!-- tabs-left -->
  <div class="vertical-tabs-container" *ngSwitchCase="'tabs-left'">
    <div class="vertical-tabs-tabs-container">
      <div class="vertical-tabs-nav-list">
        <mat-nav-list>
          <mat-list-item
            *ngFor="let viewState of pane?.viewStates; let ii = index"
            [ngClass]="{ selected: viewState.key === pane?.currentKey }"
            (click)="doChangeTabIndex(ii)"
            (contextmenu)="doContextMenu($event, viewState)"
          >
            <a tabindex="0" class="vertical-tabs-anchor">
              <div>
                <mat-icon>{{ viewState.displayIcon }}</mat-icon>
              </div>
            </a>
          </mat-list-item>
        </mat-nav-list>
      </div>
    </div>
    <div class="vertical-tabs-content">
      <div style="position: relative; height: 100%">
        <div
          class="vertical-tabs-view-host-container"
          *ngFor="let viewState of pane?.viewStates; let ii = index"
          [style.zIndex]="viewState.key === pane?.currentKey ? 10 : 0"
        >
          <porrtal-view-host [viewState]="viewState"></porrtal-view-host>
        </div>
        <div class="vertical-tabs-content-background-div"></div>
      </div>
    </div>
  </div>

  <!-- cards -->
  <div *ngSwitchCase="'cards'" class="card-container">
    <div class="cards">
      <mat-card
        #card
        *ngFor="let viewState of pane?.viewStates; let ii = index"
        class="card"
      >
        <mat-card-title style="margin: 0">
          <div
            class="card-title"
            [ngClass]="{
              'selected-card-title': viewState.key === pane?.currentKey
            }"
            (click)="doChangeTabIndex(ii)"
            (contextmenu)="doContextMenu($event, viewState)"
          >
            <mat-icon class="tab-icon">{{ viewState.displayIcon }}</mat-icon>
            <span>{{ viewState.displayText }}</span>
            <mat-icon
              (click)="doCloseTab($event, viewState)"
              inline="true"
              class="close-icon"
              >close</mat-icon
            >
          </div>
        </mat-card-title>
        <mat-card-content>
          <div class="view-host-container">
            <porrtal-view-host [viewState]="viewState"></porrtal-view-host>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</ng-container>

<!-- an hidden div is created to set the position of appearance of the menu-->
<div
  style="visibility: hidden; position: fixed"
  [style.left]="menuTopLeftPosition.x"
  [style.top]="menuTopLeftPosition.y"
  [matMenuTriggerFor]="rightMenu"
></div>

<!-- standard material menu -->
<mat-menu #rightMenu="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button mat-menu-item (click)="doCloseTab($event, viewState)">
      <span>
        <mat-icon inline="true" class="menu-close-icon">close</mat-icon>
        <span>Close Tab</span>
      </span>
    </button>
    <mat-divider></mat-divider>
    <button
      *ngIf="
        viewState?.userInfo &&
          viewState?.userInfo.length > 0 &&
          shellStateService.select('showUserInfo') | async
      "
      mat-menu-item
      [matMenuTriggerFor]="info"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon material-icons-outlined"
          >info</mat-icon
        >
        <span>Info...</span>
      </span>
    </button>
    <button
      *ngIf="
        viewState?.devInfo &&
          viewState?.devInfo.length > 0 &&
          shellStateService.select('showDevInfo') | async
      "
      mat-menu-item
      [matMenuTriggerFor]="devInfo"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon material-icons-outlined"
          >build</mat-icon
        >
        <span>Dev Info...</span>
      </span>
    </button>
    <button
      mat-menu-item
      [matMenuTriggerFor]="arrangeOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon"
          >pivot_table_chart</mat-icon
        >
        <span>Arrange...</span>
      </span>
    </button>
    <button
      mat-menu-item
      [matMenuTriggerFor]="moveOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">open_with</mat-icon>
        <span>Move To...</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #info="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doLaunch(viewLaunch)"
      mat-menu-item
      *ngFor="let viewLaunch of viewState.userInfo"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-close-icon material-icons-outlined"
          >{{ viewLaunch.state['displayIcon'] }}</mat-icon
        >
        <span>{{ viewLaunch.state['displayText'] }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #devInfo="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doLaunch(viewLaunch)"
      mat-menu-item
      *ngFor="let viewLaunch of viewState.devInfo"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-close-icon material-icons-outlined"
          >{{ viewLaunch.state['displayIcon'] }}</mat-icon
        >
        <span>{{ viewLaunch.state['displayText'] }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #arrangeOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      mat-menu-item
      (click)="doSetArrangementType($event, viewState, paneArrangement)"
      *ngFor="let paneArrangement of paneArrangements"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">{{
          pane?.arrange === paneArrangement ? 'done' : ''
        }}</mat-icon>
        <span>{{ paneArrangement }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #moveOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doMoveTab($event, viewState, paneType)"
      mat-menu-item
      *ngFor="let paneType of paneTypes"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-move-to-icon material-icons-outlined"
          >{{ moveIcons[paneType] }}</mat-icon
        >
        <span>{{ paneType }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

// libs/porrtal/r/shell-material/src/lib/view-stack/view-stack.tsx
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  CardHeader,
  Divider,
  Icon,
  Tab,
  Tabs,
  Tooltip,
} from '@mui/material';
import React, { Dispatch, useMemo } from 'react';
import {
  ShellAction,
  useShellDispatch,
  ViewHost,
  ViewStackProps,
} from '@porrtal/r-shell';
import styles from './view-stack.module.scss';
import { ContextMenu, NestedMenuItem, IconMenuItem } from 'mui-nested-menu';
import {
  paneArrangements,
  PaneType,
  paneTypes,
  ViewState,
} from '@porrtal/r-api';
import { isTemplateExpression } from 'typescript';
import { info } from 'console';

export function ViewStack(props: ViewStackProps) {
  const dispatch = useShellDispatch();
  const currentIndex = useMemo(() => {
    for (let ii = 0; ii < props.pane.viewStates.length; ii++) {
      if (props.pane.viewStates[ii].key === props.pane.currentKey) {
        return ii;
      }
    }
    return -1;
  }, [props.pane]);

  const handleChange = (event: React.SyntheticEvent, newIndex: number) => {
    dispatch({
      type: 'setCurrentViewStateByKey',
      key: props.pane.viewStates[newIndex].key,
      pane: props.pane,
    });
  };

  switch (props.pane.arrange) {
    case 'tabs-top':
      return (
        <ViewStackTabsTop
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          currentIndex={currentIndex}
          dispatch={dispatch}
          handleChange={handleChange}
          onClose={props.onClose}
        />
      );

    case 'tabs-left':
      return (
        <ViewStackTabsLeft
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          currentIndex={currentIndex}
          dispatch={dispatch}
          handleChange={handleChange}
        />
      );

    case 'cards':
      return (
        <ViewStackCards
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          currentIndex={currentIndex}
          dispatch={dispatch}
          handleChange={handleChange}
        />
      );
  }

  return (
    <div>ViewStack Arrangement ('{props.pane.arrange}') Not Supported.</div>
  );
}

function ViewStackTabsTop(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    currentIndex: number;
    handleChange: (event: React.SyntheticEvent, newIndex: number) => void;
  }
) {
  return (
    <div className={`${styles['container']} ${styles[props.pane.arrange]}`}>
      <Box
        sx={{
          borderBottom: 1,
          borderColor: 'divider',
          backgroundColor: 'gainsboro',
        }}
      >
        <Tabs
          value={props.currentIndex}
          variant="scrollable"
          scrollButtons="auto"
          onChange={props.handleChange}
          className={styles['tabs']}
        >
          {props.pane.viewStates.map((item, index) => (
            <Tab
              key={item.key}
              label={
                <ViewStackContextMenu
                  pane={props.pane}
                  showUserInfo={props.showUserInfo}
                  showDevInfo={props.showDevInfo}
                  dispatch={props.dispatch}
                  item={item}
                ></ViewStackContextMenu>
              }
            ></Tab>
          ))}
          {props.onClose && (
            <Button
              className={styles['view-stack-close-button']}
              onClick={(evt) => (props.onClose ? props.onClose(evt) : null)}
            >
              <Icon>clear</Icon>
              <span>close</span>
            </Button>
          )}
        </Tabs>
      </Box>
      <div className={styles['view-host-container']}>
        {props.pane.viewStates.map((item, index) => (
          <ViewHost
            key={item.key}
            viewState={item}
            zIndex={index === props.currentIndex ? 10 : 0}
          ></ViewHost>
        ))}
        <div
          style={{
            zIndex: 5,
            backgroundColor: 'white',
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
          }}
        ></div>
      </div>
    </div>
  );
}

function ViewStackTabsLeft(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    currentIndex: number;
    handleChange: (event: React.SyntheticEvent, newIndex: number) => void;
  }
) {
  return (
    <div className={`${styles['container']} ${styles[props.pane.arrange]}`}>
      <Box
        sx={{
          borderBottom: 1,
          borderColor: 'divider',
          backgroundColor: 'gainsboro',
        }}
      >
        <Tabs
          value={props.currentIndex}
          variant="scrollable"
          scrollButtons="auto"
          onChange={props.handleChange}
          className={styles['tabs']}
          orientation="vertical"
        >
          {props.pane.viewStates.map((item, index) => (
            <Tab
              key={item.key}
              iconPosition="start"
              label={
                <ViewStackContextMenu
                  pane={props.pane}
                  showUserInfo={props.showUserInfo}
                  showDevInfo={props.showDevInfo}
                  dispatch={props.dispatch}
                  item={item}
                ></ViewStackContextMenu>
              }
            ></Tab>
          ))}
        </Tabs>
      </Box>
      <div className={styles['view-host-container']}>
        {props.pane.viewStates.map((item, index) => (
          <ViewHost
            key={item.key}
            viewState={item}
            zIndex={index === props.currentIndex ? 10 : 0}
          ></ViewHost>
        ))}
        <div
          style={{
            zIndex: 5,
            backgroundColor: 'white',
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
          }}
        ></div>
      </div>
    </div>
  );
}

function ViewStackCards(
  props: ViewStackProps & {
    dispatch: Dispatch<ShellAction>;
    currentIndex: number;
    handleChange: (event: React.SyntheticEvent, newIndex: number) => void;
  }
) {
  return (
    <div className={styles['card-container']}>
      <div className={styles['cards']}>
        {props.pane.viewStates.map((item, index) => (
          <Card id={item.key} key={item.key} className={`${styles['card']}`}>
            <CardHeader
              sx={{
                padding: 0,
                backgroundColor:
                  index === props.currentIndex ? 'gainsboro' : '',
              }}
              title={
                <Button
                  onClick={(evt) => {
                    props.handleChange(evt, index);
                  }}
                >
                  <ViewStackContextMenu
                    pane={props.pane}
                    showUserInfo={props.showUserInfo}
                    showDevInfo={props.showDevInfo}
                    dispatch={props.dispatch}
                    item={item}
                  ></ViewStackContextMenu>
                </Button>
              }
            ></CardHeader>
            <CardContent sx={{ position: 'relative' }}>
              <div className={styles['viewHostContainer']}>
                <ViewHost key={item.key} viewState={item}></ViewHost>
              </div>
            </CardContent>
            <CardActions></CardActions>
          </Card>
        ))}
      </div>
    </div>
  );
}

export default ViewStack;

function ViewStackContextMenu(
  props: ViewStackProps & { dispatch: Dispatch<ShellAction>; item: ViewState }
) {
  const moveIcons: { [key in PaneType]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  const optionalMenus = [];
  if (props.pane.paneType !== 'search') {
    optionalMenus.push(
      <IconMenuItem
        key="close-tab"
        leftIcon={<Icon>clear</Icon>}
        label="close tab"
        onClick={
          ((evt: React.MouseEvent<HTMLElement>) => {
            props.dispatch({ type: 'deleteViewState', key: props.item.key });
            evt.stopPropagation();
          }) as () => void
        }
      ></IconMenuItem>,
      <Divider key="divider-1" />
    );
  }

  if (
    props.showUserInfo &&
    props.item.userInfo &&
    props.item.userInfo.length > 0
  ) {
    optionalMenus.push(
      <NestedMenuItem
        key={'userInfo'}
        leftIcon={<Icon>info</Icon>}
        parentMenuOpen={true}
        label={'Info...'}
      >
        {props.item.userInfo.map((info) => (
          <IconMenuItem
            key={`userInfo-${info.state ? info.state['displayText'] : 'help'}`}
            leftIcon={
              <Icon className="material-icons-outlined">
                {info.state ? info.state['displayIcon'] as string : 'help'}
              </Icon>
            }
            label={info.state ? info.state['displayText'] as string : 'help'}
            onClick={() =>
              props.dispatch({
                type: 'launchView',
                viewId: info.viewId,
                state: info.state
              })
            }
          ></IconMenuItem>
        ))}
      </NestedMenuItem>
    );
  }

  if (
    props.showDevInfo &&
    props.item.devInfo &&
    props.item.devInfo.length > 0
  ) {
    optionalMenus.push(
      <NestedMenuItem
        key={'userInfo'}
        leftIcon={<Icon>build</Icon>}
        parentMenuOpen={true}
        label={'Dev Info...'}
      >
        {props.item.devInfo.map((info) => (
          <IconMenuItem
            key={`devInfo-${info.state ? info.state['displayText'] : 'dev help'}`}
            leftIcon={
              <Icon className="material-icons-outlined">
                {info.state ? info.state['displayIcon'] as string : 'build'}
              </Icon>
            }
            label={info.state ? info.state['displayText'] as string : 'dev help'}
            onClick={() =>
              props.dispatch({
                type: 'launchView',
                viewId: info.viewId,
                state: info.state
              })
            }
          ></IconMenuItem>
        ))}
      </NestedMenuItem>
    );
  }

  if (
    (props.showUserInfo &&
      props.item.userInfo &&
      props.item.userInfo.length > 0) ||
    (props.showDevInfo && props.item.devInfo && props.item.devInfo.length > 0)
  ) {
    optionalMenus.push(<Divider key="divider-1" />);
  }

  return (
    <ContextMenu
      menuItems={[
        ...optionalMenus,
        <NestedMenuItem
          key={'arrange'}
          leftIcon={<Icon>pivot_table_chart</Icon>}
          parentMenuOpen={true}
          label={'Arrange...'}
        >
          {paneArrangements.map((paneArrangement) => (
            <IconMenuItem
              key={`arrange-${paneArrangement}`}
              leftIcon={
                <Icon className="material-icons-outlined">
                  {props.pane.arrange === paneArrangement ? 'done' : ''}
                </Icon>
              }
              label={`${paneArrangement}`}
              onClick={() =>
                props.dispatch({
                  type: 'arrangePane',
                  pane: props.pane,
                  paneArrangement,
                })
              }
            ></IconMenuItem>
          ))}
        </NestedMenuItem>,
        <NestedMenuItem
          key={'move'}
          leftIcon={<Icon>open_with</Icon>}
          parentMenuOpen={true}
          label={'Move to...'}
        >
          {paneTypes
            .filter(
              (paneType) =>
                paneType !== 'search' && paneType !== props.pane.paneType
            )
            .map((paneType) => (
              <IconMenuItem
                key={`move-to-${paneType}`}
                leftIcon={
                  <Icon className="material-icons-outlined">
                    {moveIcons[paneType]}
                  </Icon>
                }
                label={`${paneType} pane`}
                onClick={() =>
                  props.dispatch({
                    type: 'moveView',
                    key: props.item.key,
                    toPane: paneType,
                  })
                }
              ></IconMenuItem>
            ))}
        </NestedMenuItem>,
      ]}
    >
      {props.pane.arrange !== 'tabs-left' && (
        <span>
          <Icon style={{ position: 'relative', top: '5px' }}>
            {props.item.displayIcon}
          </Icon>
          &nbsp;
          {props.item.displayText}&nbsp;
          <Icon
            style={{ position: 'relative', top: '5px' }}
            onClick={(evt) => {
              props.dispatch({ type: 'deleteViewState', key: props.item.key });
              evt.stopPropagation();
            }}
          >
            clear
          </Icon>
        </span>
      )}
      {props.pane.arrange === 'tabs-left' && (
        <Tooltip title={props.item.displayText} placement="right">
          <Icon style={{ position: 'relative', top: '3px' }}>
            {props.item.displayIcon}
          </Icon>
        </Tooltip>
      )}
    </ContextMenu>
  );
}
