// libs/porrtal/r-shell-material/src/lib/logger-banner/logger-banner.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Icon } from '@mui/material';
import { useShellDispatch } from '@porrtal/r-shell';
import styles from './logger-banner.module.scss';

/* eslint-disable-next-line */
export interface LoggerBannerProps {}

export function LoggerBanner(props: LoggerBannerProps) {
  const shellDispatch = useShellDispatch();
  return (
    <Icon
      onClick={() =>
        shellDispatch({
          type: 'launchView',
          viewId: 'logger-messages',
        })
      }
    >
      notifications
    </Icon>
  );
}

export default LoggerBanner;

// libs/porrtal/a-shell-material/src/lib/logger-banner/logger-banner.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShellStateService } from '@porrtal/a-shell';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'porrtal-logger-banner',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  templateUrl: './logger-banner.component.html',
  styleUrls: ['./logger-banner.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoggerBannerComponent {
  constructor(private shellStateService: ShellStateService) {
    this.shellStateService.dispatch({
      type: 'registerView',
      view: {
        viewId: 'logger-messages',
        paneType: 'bottom',
        launchAtStartup: false,
        componentName: 'LoggerMessagesComponent',
        componentModule: () =>
          import('../logger-messages/logger-messages.component'),
        key: 'logger-messages',
        displayText: 'log',
        displayIcon: 'notifications',
      },
    });
  }

  doLaunchBannerMessages() {
    this.shellStateService.dispatch({
      type: 'launchView',
      viewId: 'logger-messages',
    });
  }
}
