// libs/porrtal-components/quick-start-demo/src/lib/viz-nav/viz-nav.tsx
import { ViewComponentProps } from '@porrtal/api';
import { useShellDispatch } from '@porrtal/shell';
import styles from './viz-nav.module.scss';

export function VizNav(props: ViewComponentProps) {
  const shellDispatch = useShellDispatch();
  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>ESRI Mapping Demos</h3>
      <div className={styles['data-container']}>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'HurricaneMap',
            })
          }
        >
          Hurricanes on the Globe
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'EarthquakeMap',
            })
          }
        >
          Earthquake Map
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'DigitalElevationMap',
            })
          }
        >
          Globe with Digital Elevation
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'BuildingSceneWithQuery',
            })
          }
        >
          Building Scene
        </h4>
      </div>
      <h3 className={styles['title']}>D3JS Charting Demos</h3>
      <div className={styles['data-container']}>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'ZoomableSunburst',
            })
          }
        >
          Zoomable Sunburst Chart
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'ZoomableCirclePack',
            })
          }
        >
          Zoomable Circle Pack Chart
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'ZoomableIcicle',
            })
          }
        >
          Zoomable Icicle Chart
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'ZoomableTreemap',
            })
          }
        >
          Zoomable Treemap Chart
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'CollapsibleTree',
            })
          }
        >
          Collapsable Tree Chart
        </h4>
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'HierarchicalBarChart',
            })
          }
        >
          Hierarchical Bar Chart
        </h4>
      </div>
    </div>
  );
}

export default VizNav;

// libs/porrtal-components/a/quick-start-demo/src/lib/viz-nav/viz-nav.component.ts
import { ChangeDetectionStrategy, Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ViewState } from '@porrtal/a-api';
import { ShellStateService } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-viz-nav',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './viz-nav.component.html',
  styleUrls: ['./viz-nav.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VizNavComponent implements OnInit {
  @Input() viewState?: ViewState;

  constructor(public shellStateService: ShellStateService) {}

  ngOnInit(): void {}
}

<div class="container">
  <h3 class="title">ESRI Mapping Demos</h3>
  <div class="data-container">
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'HurricaneMapComponent'
        })
      "
    >
      Hurricanes on the Globe
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'EarthquakeMapComponent'
        })
      "
    >
      Earthquake Map
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'DigitalElevationMapComponent'
        })
      "
    >
      Globe with Digital Elevation
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'BuildingSceneWithQueryComponent'
        })
      "
    >
      Building Scene
    </h4>
  </div>
  <h3 class="title">D3JS Charting Demos</h3>
  <div class="data-container">
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'ZoomableSunburstComponent'
        })
      "
    >
      Zoomable Sunburst Chart
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'ZoomableCirclePackComponent'
        })
      "
    >
      Zoomable Circle Pack Chart
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'ZoomableIcicleComponent'
        })
      "
    >
      Zoomable Icicle Chart
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'ZoomableTreemapComponent'
        })
      "
    >
      Zoomable Treemap Chart
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'CollapsibleTreeComponent'
        })
      "
    >
      Collapsable Tree Chart
    </h4>
    <h4
      class="link-button"
      (click)="
        shellStateService.dispatch({
          type: 'launchView',
          viewId: 'HierarchicalBarChartComponent'
        })
      "
    >
      Hierarchical Bar Chart
    </h4>
  </div>
</div>
