// libs/porrtal/r-shell-blueprint/src/lib/maximize-host/maximize-host.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Icon } from '@blueprintjs/core';
import { useShellDispatch } from '@porrtal/r-shell';
import { MaximizeHostProps } from '@porrtal/r-shell';
import { useEffect, useRef } from 'react';

import styles from './maximize-host.module.scss';

export function MaximizeHost(props: MaximizeHostProps) {
  const maximizeHostRef = useRef<HTMLDivElement>(null);
  const shellDispatch = useShellDispatch();
  useEffect(() => {
    if (props.htmlEl && maximizeHostRef.current) {
      maximizeHostRef.current.appendChild(props.htmlEl);
    }
  }, [props.htmlEl, maximizeHostRef.current]);

  return (
    <div className={styles['container']} style={{ zIndex: props.zIndex }}>
      <div className={styles['header']}>
        <div>{props.maximizeText}</div>
          <Icon
            onClick={() => {
              shellDispatch({
                type: 'restoreMaximized',
              });
              props.restore?.();
            }}
            icon="minimize"
          ></Icon>
      </div>
      {/* </mat-toolbar> */}
      <div className={styles['content']}>
        <div ref={maximizeHostRef} className={styles['maximize-host']}></div>
      </div>
    </div>
  );
}

// libs/porrtal/a-shell-material/src/lib/maximize-host/maximize-host.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MaximizeItem, ShellStateService } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-maximize-host',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatToolbarModule],
  templateUrl: './maximize-host.component.html',
  styleUrls: ['./maximize-host.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MaximizeHostComponent implements OnDestroy, AfterViewInit {

  @Input() 
  maximizeItem?: MaximizeItem

  @ViewChild('maximizeHost', { read: ElementRef, static: true })
  maximizeHost?: ElementRef<HTMLDivElement>;

  zIndex = 9900;

  constructor(private shellStateService: ShellStateService) {}

  restoreMaximizeItem() {
    console.log('restore from maximize.', this.maximizeItem);
    this.shellStateService.dispatch({ type: 'restoreMaximized' });
    this.maximizeItem?.restore?.();
  }

  ngAfterViewInit() {
    if (this.maximizeItem && this.maximizeHost) {
      console.log('maximize-host: appendChild', this.maximizeItem);
      this.maximizeHost.nativeElement.appendChild(this.maximizeItem.htmlEl);
    } else {
      console.log(
        'error.  maximize-host component: afterViewInit: items not defined.'
      );
    }
  };

  ngOnDestroy() {};
}

<div class="container mat-app-background" [style.z-index]="maximizeItem?.zIndex">
  <mat-toolbar color="accent" class="header">
    <div>{{ maximizeItem?.maximizeText }}</div>
    <button mat-button (click)="restoreMaximizeItem()" class="restore-button">
      <mat-icon class="restore-icon">close_fullscreen</mat-icon>
    </button>
  </mat-toolbar>
  <div class="content">
    <div #maximizeHost class="maximize-host"></div>
  </div>
</div>
