// libs/porrtal/r-shell/src/lib/view-host/view-host.tsx
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import React, {
  ComponentType,
  LazyExoticComponent,
  Suspense,
  useEffect,
  useState,
} from 'react';
import { ViewComponentProps, ViewState } from '@porrtal/r-api';
import styles from './view-host.module.scss';

export interface ViewHostProps {
  viewState: ViewState;
  onTop?: boolean;
}

export function ViewHost(props: ViewHostProps) {
  console.log(`in view host...`);
  const [DynComp, setDynComp] =
    useState<LazyExoticComponent<ComponentType<ViewComponentProps>>>();

  useEffect(() => {
    if (props.viewState.componentImport) {
      setDynComp(React.lazy(props.viewState.componentImport));
      console.log(`in view host use effect...`);
    }
  }, [props.viewState.componentImport]);

  return (
    <div
      key={props.viewState.key}
      className={`${styles['container']} ${props.onTop ? styles['onTop'] : ''}`}
    >
      <div className={styles['innerContainer']}>
        {DynComp ? (
          <DynComp viewState={props.viewState} />
        ) : (
          <div>loading...</div>
        )}
      </div>
    </div>
  );
}

export default ViewHost;

// libs/porrtal/a-shell/src/lib/view-host/view-host.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  OnInit,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { ViewComponentProps, ViewState } from '@porrtal/a-api';

@Component({
  selector: 'porrtal-view-host',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './view-host.component.html',
  styleUrls: ['./view-host.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ViewHostComponent {
  private _viewState!: ViewState;
  @Input() public set viewState(value: ViewState) {
    this._viewState = value;
    this.loadViewStateComponent();
  }
  public get viewState() {
    return this._viewState;
  }

  private _containerRef!: ViewContainerRef;
  @ViewChild('containerRef', { read: ViewContainerRef })
  public set containerRef(value: ViewContainerRef) {
    this._containerRef = value;
    this.loadViewStateComponent();
  }
  public get containerRef() {
    return this._containerRef;
  }

  constructor(private viewContainerRef: ViewContainerRef) {}

  async loadViewStateComponent() {
    if (this.viewState && this.containerRef) {
      this.containerRef.clear();
      const component = await this.viewState.componentImport();
      if (component) {
        const comp =
          this.containerRef.createComponent<ViewComponentProps>(component);

        comp.setInput('viewState', this._viewState);
        comp.changeDetectorRef.markForCheck();
        comp.changeDetectorRef.detectChanges();
      }
    }
  }
}

<div class="container">
  <div class="container-content">
    <ng-container #containerRef></ng-container>
  </div>
</div>
