// apps/porrtal-auth/a-strapi-app/src/app/views/v3/v3.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-workspace-v3',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './v3.component.html',
  styleUrls: ['./v3.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class V3Component {}

// apps/porrtal-auth/n-mock-app/views/v3/v3.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './v3.module.scss';

/* eslint-disable-next-line */
export interface V3Props {}

export function V3(props: V3Props) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to V3!</h1>
    </div>
  );
}

export default V3;
