// apps/porrtal-auth/a-zso/strapi-app/src/app/pages/two/two.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { View } from '@porrtal/a-api';
import { BannerData, ShellStateService } from '@porrtal/a-shell';
import { ShellLayoutComponent } from '@porrtal/a-shell-material';

@Component({
  selector: 'app-two',
  standalone: true,
  imports: [CommonModule, ShellLayoutComponent],
  templateUrl: './two.component.html',
  styleUrls: ['./two.component.scss'],
})
export class TwoComponent {
  porrtalViews: View[] = [
    {
      key: 'Main2',
      launchAtStartup: true,
      displayText: 'Main2',
      paneType: 'main',
      displayIcon: 'updated',
      componentName: 'Main2Component',
      componentModule: () => import('../../views/main2/main2.component'),
    },
  ];
  
  porrtalBanner: BannerData = {
    // uncomment and edit this code if you would like a banner image
    // bannerImageUrl: './assets/my-banner.png',
    // bannerImageHeight: 63,
    // bannerImageWidth: 500,
    displayText: 'My App - Two',
    displayIcon: 'cyclone',
    childData: [
      {
        displayText: 'My App - One',
        displayIcon: 'cyclone',
        targetUrl: '/one',
      },
    ],
  };

  constructor(public shellStateService: ShellStateService) {
    this.porrtalViews.forEach((view) =>
      shellStateService.dispatch({
        type: 'registerView',
        view,
      })
    );

    shellStateService.dispatch({
      type: 'launchStartupViews',
    });
  }
}

// apps/porrtal-auth/n-msal-app/pages/two/index.tsx
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import '@blueprintjs/popover2/lib/css/blueprint-popover2.css';

import { View } from '@porrtal/r-api';
import { useEffect, useState } from 'react';
import styles from './index.module.scss';
import Head from 'next/head';
import { ShellState } from '@porrtal/r-shell';
import { ShellBlueprint } from '@porrtal/r-shell-blueprint';
import { MsalAuthentication } from '@porrtal/r-user-msal';
import { msalConfig } from '../../msal-config';

/* eslint-disable-next-line */
export interface TwoProps {}

export function Two(props: TwoProps) {
  const views: View[] = [
    {
      viewId: 'main-view',
      paneType: 'main',
      launchAtStartup: true,
      componentName: 'MainView',
      componentModule: () => import('../../views/main-view/main-view'),
      key: 'main-view',
      displayText: 'main-view',
      displayIcon: 'home',
    },
    {
      viewId: 'nav-view',
      paneType: 'nav',
      launchAtStartup: true,
      componentName: 'NavView',
      componentModule: () => import('../../views/nav-view/nav-view'),
      key: 'nav-view',
      displayText: 'nav-view',
      displayIcon: 'feed',
    },
    {
      viewId: 'profile',
      paneType: 'right',
      launchAtStartup: true,
      componentName: 'Profile',
      componentModule: () => import('../../views/profile/profile'),
      key: 'profile',
      displayText: 'profile',
      displayIcon: 'user',
    },
    {
      viewId: 'v1',
      paneType: 'bottom',
      launchAtStartup: true,
      componentName: 'V1',
      componentModule: () => import('../../views/v1/v1'),
      key: 'v1',
      permissions: 'second:role1',
      displayText: 'v1',
      displayIcon: 'cube',
    },
    {
      viewId: 'v2',
      paneType: 'bottom',
      launchAtStartup: true,
      componentName: 'V2',
      componentModule: () => import('../../views/v2/v2'),
      key: 'v2',
      permissions: 'primary:public',
      displayText: 'v2',
      displayIcon: 'cube',
    },
    {
      viewId: 'v3',
      paneType: 'bottom',
      launchAtStartup: true,
      componentName: 'V3',
      componentModule: () => import('../../views/v3/v3'),
      key: 'v3',
      permissions: 'second:role6',
      entityType: 'account',
      displayText: 'v3',
      displayIcon: 'cube',
    },
    {
      viewId: 'v4',
      paneType: 'bottom',
      launchAtStartup: true,
      componentName: 'V4',
      componentModule: () => import('../../views/v4/v4'),
      key: 'v4',
      permissions: 'orphan-auth-z:no-role',
      displayText: 'v4',
      displayIcon: 'cube',
    },
    {
      viewId: 'shell-state-dashboard',
      paneType: 'bottom',
      launchAtStartup: false,
      componentName: 'ShellStateDashboard',
      componentModule: () => import('@porrtal/r-shell-blueprint'),
      key: 'shell-state-dashboard',
      displayText: 'Shell State Dashboard',
      displayIcon: 'key',
    },
  ];

  const [isSSR, setIsSSR] = useState(true);

  useEffect(() => {
    setIsSSR(false);
  }, []);

  if (!isSSR) {
    return (
      <>
        <Head>
          <title>@porrtal - porrtal-auth - n-auth0-app (material)</title>
        </Head>

        <ShellState views={views}>
          <MsalAuthentication msalConfig={msalConfig}>
            <ShellBlueprint
              bannerData={{
                displayText: 'porrtal-auth - nextjs - msal (blueprint)',
                displayIcon: 'hurricane',
                childData: [
                  {
                    displayText: 'one',
                    targetUrl: '/',
                  },
                  {
                    displayText: 'two',
                    targetUrl: '/two',
                  },
                ],
              }}
            />
          </MsalAuthentication>
        </ShellState>
      </>
    );
  }

  return <div>loading...</div>;
}

export default Two;
