// apps/a/porrtal-app/src/app/quick-start-demo/quick-start-demo.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShellStateService } from '@porrtal/a-shell';
import { View } from '@porrtal/a-api';
import { ShellLayoutComponent } from '@porrtal/a-shell-material';

const views: View[] = [
  {
    displayText: 'Create Account',
    displayIcon: 'account_box',
    componentName: 'AccountCreateComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'Account {accountId}',
    displayText: 'Account {accountId}',
    displayIcon: 'account_box',
    componentName: 'AccountDetailComponent',
    entityType: 'account',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'Billing {accountId}',
    displayText: 'Billing {accountId}',
    displayIcon: 'account_box',
    componentName: 'AccountBillingHistoryComponent',
    entityType: 'account',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'AccountNav',
    launchAtStartup: true,
    displayText: 'Account Navigation',
    paneType: 'nav',
    displayIcon: 'account_box',
    componentName: 'AccountNavComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'AccountSearch',
    launchAtStartup: true,
    displayText: 'Account',
    paneType: 'search',
    displayIcon: 'account_box',
    componentName: 'AccountSearchComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Create Appointment',
    displayIcon: 'calendar_month',
    componentName: 'AppointmentCreateComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'Appointment {appointmentId}',
    displayText: 'Appointment {appointmentId}',
    displayIcon: 'calendar_month',
    componentName: 'AppointmentDetailComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'AppointmentLocationMap {appointmentId}',
    displayText: 'Map {appointmentId}',
    displayIcon: 'calendar_month',
    componentName: 'AppointmentLocationMapComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'AppointmentNav',
    launchAtStartup: true,
    displayText: 'Appointment Navigation',
    paneType: 'nav',
    displayIcon: 'calendar_month',
    componentName: 'AppointmentNavComponent',
    componentModule: () => {
      console.log('appointment nav component module function called...');
      return import('@porrtal-components/a-quick-start-demo');
    },
  },
  {
    key: 'AppointmentSearch',
    launchAtStartup: true,
    displayText: 'Appointment',
    paneType: 'search',
    displayIcon: 'calendar_month',
    componentName: 'AppointmentSearchComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'AppointmentNav',
    launchAtStartup: true,
    displayText: 'Appointment Navigation',
    paneType: 'nav',
    displayIcon: 'calendar_month',
    componentName: 'AppointmentNavComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    key: 'VizNav',
    launchAtStartup: true,
    displayText: 'Viz Demos',
    paneType: 'nav',
    displayIcon: 'map',
    componentName: 'VizNavComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Buildings',
    displayIcon: 'office',
    componentName: 'BuildingSceneWithQueryComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Earth',
    displayIcon: 'globe',
    componentName: 'DigitalElevationMapComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Hurricane',
    displayIcon: 'git-commit',
    componentName: 'HurricaneMapComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Earthquake',
    displayIcon: 'inner-join',
    componentName: 'EarthquakeMapComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Collapse Tree Chart',
    displayIcon: 'diagram-tree',
    componentName: 'CollapsibleTreeComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Bar Chart',
    displayIcon: 'diagram-tree',
    componentName: 'HierarchicalBarChartComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Icicle Chart',
    displayIcon: 'diagram-tree',
    componentName: 'ZoomableIcicleComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Sunburst Chart',
    displayIcon: 'diagram-tree',
    componentName: 'ZoomableSunburstComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Treemap Chart',
    displayIcon: 'diagram-tree',
    componentName: 'ZoomableTreemapComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
  {
    displayText: 'Circle Pack Chart',
    displayIcon: 'diagram-tree',
    componentName: 'ZoomableCirclePackComponent',
    componentModule: () => import('@porrtal-components/a-quick-start-demo'),
  },
];

@Component({
  selector: 'porrtal-quick-start-demo',
  standalone: true,
  imports: [CommonModule, ShellLayoutComponent],
  templateUrl: './quick-start-demo.component.html',
  styleUrls: ['./quick-start-demo.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class QuickStartDemoComponent {
  constructor(public shellStateService: ShellStateService) {
    views.forEach((view) =>
      shellStateService.dispatch({
        type: 'registerView',
        view,
      })
    );

    shellStateService.dispatch({
      type: 'launchStartupViews',
    });
  }
}

<p>quick-start-demo works!</p>

// apps/porrtal-app/pages/quick-start-demo/index.tsx
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import '@blueprintjs/popover2/lib/css/blueprint-popover2.css';

import { ShellState } from '@porrtal/shell';
import { Auth0Authentication } from '@porrtal/user';
import { ShellBlueprint } from '@porrtal/shell-blueprint';
import { useEffect, useState } from 'react';
import { View } from '@porrtal/api';

/* eslint-disable-next-line */
export interface QuickStartDemoProps {}

export function QuickStartDemo(props: QuickStartDemoProps) {
  const [isSSR, setIsSSR] = useState(true);

  useEffect(() => {
    setIsSSR(false);
  }, []);

  const views: View[] = [
    {
      displayText: 'Create Account',
      displayIcon: 'mugshot',
      componentName: 'AccountCreate',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'Account {accountId}',
      displayText: 'Account {accountId}',
      displayIcon: 'mugshot',
      componentName: 'AccountDetail',
      entityType: 'account',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'Billing {accountId}',
      displayText: 'Billing {accountId}',
      displayIcon: 'mugshot',
      componentName: 'AccountBillingHistory',
      entityType: 'account',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'AccountNav',
      launchAtStartup: true,
      displayText: 'Account Navigation',
      paneType: 'nav',
      displayIcon: 'mugshot',
      componentName: 'AccountNav',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'AccountSearch',
      launchAtStartup: true,
      displayText: 'Account',
      paneType: 'search',
      displayIcon: 'mugshot',
      componentName: 'AccountSearch',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Create Appointment',
      displayIcon: 'calendar',
      componentName: 'AppointmentCreate',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'Appointment {appointmentId}',
      displayText: 'Appointment {appointmentId}',
      displayIcon: 'calendar',
      componentName: 'AppointmentDetail',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'AppointmentLocationMap {appointmentId}',
      displayText: 'Map {appointmentId}',
      displayIcon: 'calendar',
      componentName: 'AppointmentLocationMap',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'AppointmentNav',
      launchAtStartup: true,
      displayText: 'Appointment Navigation',
      paneType: 'nav',
      displayIcon: 'calendar',
      componentName: 'AppointmentNav',
      componentModule: () => {
        console.log('appointment nav component module function called...')
        return import('@porrtal-components/quick-start-demo');
      }
    },
    {
      key: 'AppointmentSearch',
      launchAtStartup: true,
      displayText: 'Appointment',
      paneType: 'search',
      displayIcon: 'calendar',
      componentName: 'AppointmentSearch',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'AppointmentNav',
      launchAtStartup: true,
      displayText: 'Appointment Navigation',
      paneType: 'nav',
      displayIcon: 'calendar',
      componentName: 'AppointmentNav',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      key: 'VizNav',
      launchAtStartup: true,
      displayText: 'Viz Demos',
      paneType: 'nav',
      displayIcon: 'map',
      componentName: 'VizNav',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Buildings',
      displayIcon: 'office',
      componentName: 'BuildingSceneWithQuery',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Earth',
      displayIcon: 'globe',
      componentName: 'DigitalElevationMap',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Hurricane',
      displayIcon: 'git-commit',
      componentName: 'HurricaneMap',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Earthquake',
      displayIcon: 'inner-join',
      componentName: 'EarthquakeMap',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Collapse Tree Chart',
      displayIcon: 'diagram-tree',
      componentName: 'CollapsibleTree',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Bar Chart',
      displayIcon: 'diagram-tree',
      componentName: 'HierarchicalBarChart',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Icicle Chart',
      displayIcon: 'diagram-tree',
      componentName: 'ZoomableIcicle',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Sunburst Chart',
      displayIcon: 'diagram-tree',
      componentName: 'ZoomableSunburst',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Treemap Chart',
      displayIcon: 'diagram-tree',
      componentName: 'ZoomableTreemap',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
    {
      displayText: 'Circle Pack Chart',
      displayIcon: 'diagram-tree',
      componentName: 'ZoomableCirclePack',
      componentModule: () => import('@porrtal-components/quick-start-demo'),
    },
  ];

  if (!isSSR) {
    return (
      <Auth0Authentication
        domain="dev-b6h3bfnp.us.auth0.com"
        clientId="uP4eHSspiDjg6E7GKU5LjdFPn0WwEKTq"
        redirectUri="http://localhost:4200"
      >
        <ShellState views={views}>
          <ShellBlueprint />
        </ShellState>
      </Auth0Authentication>
    );
  }

  return <div>loading....</div>;
}

export default QuickStartDemo;
