// libs/porrtal/a-shell-material/src/lib/user-banner/user-banner.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  ChangeDetectionStrategy,
  Component,
  Inject,
  Optional,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  AuthNInterface,
  AUTH_N_INTERFACE,
  LoginStrategy,
} from '@porrtal/a-user';
import { LoginService } from './login-service/login.service';
import { MatDialogModule } from '@angular/material/dialog';
import { Observable } from 'rxjs';

@Component({
  selector: 'porrtal-user-banner',
  standalone: true,
  imports: [CommonModule, MatDialogModule],
  providers: [LoginService],
  templateUrl: './user-banner.component.html',
  styleUrls: ['./user-banner.component.scss'],
  changeDetection: ChangeDetectionStrategy.Default,
})
export class UserBannerComponent {

  constructor(
    @Optional() @Inject(AUTH_N_INTERFACE) public authN: AuthNInterface | null,
    public loginService: LoginService
  ) {
    console.log('UserBannerComponent constructor...', authN);

    authN?.init?.();
  }

  login(loginStrategy: LoginStrategy) {
    if (loginStrategy === 'loginWithRedirect') {
      this?.authN?.loginWithRedirect && this.authN.loginWithRedirect();
    } else {
      const x = this.loginService
        .getUserLoginData(loginStrategy)
        .subscribe((userLoginData) => {
          switch (userLoginData.type) {
            case 'login':
              this?.authN?.login &&
                this.authN.login({
                  identifier: userLoginData.identifier,
                  password: userLoginData.password,
                });
              break;

            case 'register':
              this?.authN?.register &&
                this.authN.register({
                  username: userLoginData.user,
                  email: userLoginData.email,
                  password: userLoginData.password,
                });
              break;

            default:
              break;
          }
        });
    }
  }
}

<span *ngIf="authN && (authN.authNState$ | async) === 'authenticated'">
  <span style="margin-right: 6px">{{ (authN.user$ | async)?.name }}</span>
  <button (click)="authN.logout?.()">logout</button>
</span>
<ng-container *ngIf="authN && (authN.authNState$ | async) !== 'authenticated'">
  <ng-container *ngIf="authN.loginStrategy$ | async as loginStrategy">
    <button (click)="login(loginStrategy)" class="login-button" [disabled]="(authN.authNState$ | async) === 'authenticating'">
      <mat-spinner
        class="spinner"
        [diameter]="16"
        *ngIf="(authN.authNState$ | async) === 'authenticating'"
      ></mat-spinner>
      <mat-icon
        class="error-icon"
        *ngIf="(authN.authNState$ | async) === 'error'"
        color="warn"
        inline="true"
        [matTooltip]="(authN.errorMessage$ | async) ?? ''"
        >report</mat-icon
      >
      <div
        *ngIf="
          !['authenticating', 'error'].includes((authN.authNState$ | async) ?? '')
        "
      ></div>
      <span> login </span>
    </button>
  </ng-container>
  <div *ngIf="!authN"></div>
</ng-container>

// libs/porrtal/r-shell-blueprint/src/lib/user-banner/user-banner.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { useAuth } from '@porrtal/r-user';
import { useState } from 'react';
import LoginDialog from './login-dialog/login-dialog';
import styles from './user-banner.module.scss';

/* eslint-disable-next-line */
export interface UserBannerProps {}

export function UserBanner(props: UserBannerProps) {
  const auth = useAuth();
  const [open, setOpen] = useState(false);

  console.log(
    `UserBanner: auth def'd(${auth ? 'true' : 'false'}), isAuthenticated('${
      auth?.isAuthenticated
    }'), isInitialized('${auth?.isInitialized}')`
  );
  if (auth?.isInitialized) {
    return (
      <div className={styles['container']}>
        {auth?.isAuthenticated && (
          <span className={styles['user-name']}>{auth?.user?.name}</span>
        )}
        {!auth?.isAuthenticated && (
          <button
            onClick={() => {
              if (!auth) {
                return;
              }
              switch (auth.loginStrategy) {
                case 'loginWithRedirect':
                  auth?.loginWithRedirect ? auth?.loginWithRedirect() : null;
                  break;

                case 'login':
                case 'loginAndRegister':
                  setOpen(true);
                  break;
              }
            }}
          >
            Login
          </button>
        )}
        {auth?.isAuthenticated && (
          <button onClick={() => (auth?.logout ? auth?.logout() : null)}>
            Logout
          </button>
        )}
        <LoginDialog
          open={open}
          loginStrategy={
            auth.loginStrategy === 'loginWithRedirect'
              ? 'login'
              : 'loginAndRegister'
          }
          onClose={(result) => {
            if (result.type === 'login') {
              auth.login &&
                auth.login({
                  identifier: result.identifier,
                  password: result.password,
                });
            }

            if (result.type === 'register') {
              auth.register &&
                auth.register({
                  username: result.user,
                  email: result.email,
                  password: result.password,
                });
            }

            setOpen(false);
          }}
        ></LoginDialog>
      </div>
    );
  } else {
    return <div className={styles['container']}>loading...</div>;
  }
}

export default UserBanner;
