// apps/porrtal-auth/a-auth0-app/src/app/views/v1/v1.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-workspace-v1',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './v1.component.html',
  styleUrls: ['./v1.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class V1Component {}

// apps/porrtal-auth/n-msal-app/views/v1/v1.tsx
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { useAuthNGetToken } from '@porrtal/r-user';
import styles from './v1.module.scss';
import { useEffect, useState } from 'react';

/* eslint-disable-next-line */
export interface V1Props {}

export function V1(props: V1Props) {
  const getToken = useAuthNGetToken();

  // add a state variable to hold the token
  const [token, setToken] = useState<string | undefined>(undefined);

  // add an effect to get the token into a state variable
  useEffect(() => {
    getToken(['api://5fc81598-8a0d-41a8-b2d9-df887fedf2a6/basic-access'])
      .then((token) => {
        setToken(token);
      });
  });


  return (
    <div className={styles['container']}>
      <h1>Welcome to V1!</h1>
      <p>
        {token ? `Your token is ${token}` : 'You are not logged in'}
      </p>
    </div>
  );
}

export default V1;
