// libs/porrtal-components/r-quick-start-demo/src/lib/esri/earthquake/earthquake-map/earthquake-map.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './earthquake-map.module.scss';

/* eslint-disable-next-line */
export interface EarthquakeMapProps {}

export function EarthquakeMap(props: EarthquakeMapProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to EarthquakeMap!</h1>
    </div>
  );
}

export default EarthquakeMap;

// libs/porrtal-components/a-quick-start-demo/src/lib/esri/earthquake/earthquake-map/earthquake-map.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-earthquake-map',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './earthquake-map.component.html',
  styleUrls: ['./earthquake-map.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EarthquakeMapComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>earthquake-map works!</p>
