// libs/porrtal-components/a-quick-start-material/src/lib/docs-nav/docs-nav.component.ts
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ViewState } from '@porrtal/a-api';
import { ShellStateService } from '@porrtal/a-shell';
import { MatIconModule } from '@angular/material/icon';
import { docsNavViews } from './docs-nav-views';

@Component({
  selector: 'porrtal-workspace-docs-nav',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  templateUrl: './docs-nav.component.html',
  styleUrls: ['./docs-nav.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DocsNavComponent {
  @Input() viewState?: ViewState;

  constructor(public shellStateService: ShellStateService) {
    docsNavViews.forEach((v) => {
      this.shellStateService.dispatch({
        type: 'registerView',
        view: v,
      });
    });

    this.shellStateService.dispatch({
      type: 'launchView',
      viewId: 'Welcome',
    });

  }
}

<div class='container'>
    <h3 class='title'>Quick Start Docs</h3>
    <div class='data-container'>
      <!-- Welcome -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Welcome'
          })
        "
      >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Welcome !!</span>
      </h4>

      <!-- Setup Your Workstation -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Setup Your Workstation'
          })
        "
      >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Setup Your Workstation</span>
      </h4>

      <!-- Create the App -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Create the App'
          })
          "
          >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Create the App</span>
      </h4>

      <!-- Create the Nav Component -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Create the Nav Component'
          })
          "
          >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Create the Nav Component</span>
      </h4>

      <!-- Launch a Component -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Launch a Component'
          })
          "
          >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Launch a Component</span>
      </h4>

      <!-- Create an Entity Menu -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Create an Entity Menu'
          })
          "
          >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Create an Entity Menu</span>
      </h4>

      <!-- Create a Search Component -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Create a Search Component'
          })
          "
          >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Create a Search Component</span>
      </h4>

      <!-- Next Steps -->
      <h4
        class='link-button'
        (click)="
          shellStateService.dispatch({
            type: 'launchView',
            viewId: 'Next Steps'
          })
          "
          >
        <mat-icon>auto_awesome</mat-icon>
        <span style="margin-left: '5px'">Next Steps</span>
      </h4>
    </div>
  </div>

// libs/porrtal-components/r-quick-start-blueprint/src/lib/docs-nav/docs-nav.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Icon } from '@blueprintjs/core';
import { useEffect } from 'react';
import { useShellDispatch } from '@porrtal/r-shell';
import styles from './docs-nav.module.scss';
import { docsNavViews } from './docs-nav-views';

/* eslint-disable-next-line */
export interface DocsNavProps {}

export function DocsNav(props: DocsNavProps) {
  const shellDispatch = useShellDispatch();
  useEffect(() => {
    if (shellDispatch) {
      docsNavViews.forEach((v) => {
        shellDispatch({
          type: 'registerView',
          view: v,
        });
      });

      shellDispatch({
        type: 'launchView',
        viewId: 'Welcome',
      });
    }
  }, [shellDispatch]);

  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>Quick Start Docs</h3>
      <div className={styles['data-container']}>
        {/* Welcome */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Welcome',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Welcome !!</span>
        </h4>

        {/* Setup Your Workstation */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Setup Your Workstation',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Setup Your Workstation</span>
        </h4>

        {/* Create the App */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Create the App',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Create the App</span>
        </h4>

        {/* Create the Nav Component */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Create the Nav Component',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Create the Nav Component</span>
        </h4>

        {/* Launch a Component */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Launch a Component',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Launch a Component</span>
        </h4>

        {/* Create an Entity Menu */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Create an Entity Menu',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Create an Entity Menu</span>
        </h4>

        {/* Create a Search Component */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Create a Search Component',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Create a Search Component</span>
        </h4>

        {/* Next Steps */}
        <h4
          className={styles['link-button']}
          onClick={() =>
            shellDispatch({
              type: 'launchView',
              viewId: 'Next Steps',
            })
          }
        >
          <Icon icon="clean" />
          <span style={{ marginLeft: '5px' }}>Next Steps</span>
        </h4>
      </div>
    </div>
  );
}

export default DocsNav;
