// libs/porrtal-components/r-quick-start-demo/src/lib/hierarchy/zoomable-icicle/zoomable-icicle.tsx
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './zoomable-icicle.module.scss';

/* eslint-disable-next-line */
export interface ZoomableIcicleProps {}

export function ZoomableIcicle(props: ZoomableIcicleProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to ZoomableIcicle!</h1>
    </div>
  );
}

export default ZoomableIcicle;

// libs/porrtal-components/a-quick-start-demo/src/lib/hierarchy/zoomable-icicle/zoomable-icicle.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-zoomable-icicle',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './zoomable-icicle.component.html',
  styleUrls: ['./zoomable-icicle.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ZoomableIcicleComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>zoomable-icicle works!</p>
