// libs/porrtal-components/quick-start-demo/src/lib/appointment/appointment-detail/appointment-detail.tsx
import { ViewComponentProps } from '@porrtal/api';
import { useEffect, useState } from 'react';
import Moment from 'moment';
import {
  Appointment,
  AppointmentData,
  fetchAppointmentData,
} from '../../data/appointment-data';
import styles from './appointment-detail.module.scss';

export function AppointmentDetail(props: ViewComponentProps) {
  const [appointmentData, setAppointmentData] = useState<AppointmentData>();
  const [appointment, setAppointment] = useState<
    Appointment | null | undefined
  >();
  useEffect(() => {
    fetchAppointmentData(500).then((d) => {
      setAppointmentData(d);
      const currentAppointment = d?.find(
        (appt) =>
          appt.appointmentId === props.viewState?.state?.['appointmentId']
      );
      setAppointment(currentAppointment);
    });
  }, [props.viewState]);

  if (appointment === undefined) {
    return <div>loading appointment data...</div>;
  }

  if (appointment === null) {
    return (
      <div>
        <span>appointmentId:&nbsp;</span>
        <span>{`${props.viewState?.state?.['appointmentId']}`}</span>
        <span>&nbsp;not found.</span>
      </div>
    );
  }

  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>
        {appointment?.item} ({appointment?.appointmentId}) - Appointment Detail
      </h3>
      <div className={styles['data-container']}>
        <h4>{Moment(appointment.date).format('YYYY-MM-DD, h:mm a')} - {appointment.duration / (1000 * 60)} minutes.</h4>
        <p>{appointment.description}</p>
      </div>
    </div>
  );
}

export default AppointmentDetail;

// libs/porrtal-components/a/quick-start-demo/src/lib/appointment/appointment-detail/appointment-detail.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ViewState } from '@porrtal/a-api';
import { Appointment, appointmentData } from '../../data/appointment-data';
import * as Moment from 'moment';

@Component({
  selector: 'porrtal-appointment-detail',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './appointment-detail.component.html',
  styleUrls: ['./appointment-detail.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppointmentDetailComponent {
  private _viewState?: ViewState;
  @Input() set viewState(value: ViewState | undefined) {
    console.log('appointment detail - view state', value);
    this._viewState = value;
    if (this._viewState?.state && this._viewState?.state['appointmentId']) {
      this.loading = false;
      this.appointmentId = this._viewState?.state['appointmentId'] as number;
      this.appointment = appointmentData.find(
        (appointment) => appointment.appointmentId === this.appointmentId
      );
      if (!this.appointment) {
        this.notFound = true;
      }
    }
    console.log(`loading: ${this.loading}, notFound: ${this.notFound}`)
  }
  get viewState() {
    return this._viewState;
  }

  public loading = true;
  public notFound = false;

  public Moment = Moment;
  public appointment?: Appointment;
  public appointmentId?: number;
}

<!-- found and loaded appointment -->
<div *ngIf="!loading && !notFound" class="container">
  <h3 class="title">
    {{ appointment?.item }} ({{ appointment?.appointmentId }}) - Appointment
    Detail
  </h3>
  <div class="data-container">
    <h4>
      {{ Moment(appointment?.date).format('YYYY-MM-DD, h:mm a') }} -{{ ' ' }}
      {{ (appointment?.duration ?? 0) / (1000 * 60) }} minutes.
    </h4>
    <p>{{ appointment?.description }}</p>
  </div>
</div>

<!-- loading appointment -->
<ng-container *ngIf="loading">
  <div>loading appointment data...</div>
</ng-container>

<!-- didn't find appointment -->
<ng-container *ngIf="notFound">
  <div>
    <span>appointmentId:&nbsp;</span>
    <span>{{appointmentId}}</span>
    <span>&nbsp;not found.</span>
  </div>
</ng-container>
