// libs/porrtal/r-user/src/lib/user-banner/user-banner.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import LoginButton from '../login-button/login-button';
import LogoutButton from '../logout-button/logout-button';
import useAuth from '../use-auth/use-auth';
import styles from './user-banner.module.scss';

/* eslint-disable-next-line */
export interface UserBannerProps {}

export function UserBanner(props: UserBannerProps) {
  const auth = useAuth();

  console.log(`UserBanner: auth def'd(${auth ? 'true' : 'false'}), isAuthenticated('${auth?.isAuthenticated}'), isInitialized('${auth?.isInitialized}')`);
  if (auth?.isInitialized) {
    return (
      <div className={styles['container']}>
        {auth?.isAuthenticated && <span className={styles['user-name']}>{auth?.user?.name}</span>}
        {!auth?.isAuthenticated && <LoginButton />}
        {auth?.isAuthenticated && <LogoutButton />}
      </div>
    );
  } else {
    return <div className={styles['container']}>loading...</div>;
  }
}

export default UserBanner;

// libs/porrtal/a-shell-material/src/lib/user-banner/user-banner.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, Inject, Optional } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthNInterface, AUTH_N_INTERFACE } from '@porrtal/a-user';
import { UserLoginButtonComponent } from '../user-login-button/user-login-button.component';
import { UserLogoutButtonComponent } from '../user-logout-button/user-logout-button.component';

@Component({
  selector: 'porrtal-user-banner',
  standalone: true,
  imports: [CommonModule, UserLoginButtonComponent, UserLogoutButtonComponent],
  templateUrl: './user-banner.component.html',
  styleUrls: ['./user-banner.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UserBannerComponent {
  constructor(@Optional() @Inject(AUTH_N_INTERFACE) public authN: AuthNInterface) {}
}

<span *ngIf="authN && (authN.authNState$ | async) === 'authenticated'">
  <span style="margin-right: 6px">{{ (authN.user$ | async)?.name }}</span>
  <button (click)="authN.logout?.()">logout</button>
</span>
<ng-container *ngIf="authN && (authN.authNState$ | async) !== 'authenticated'">
  <ng-container *ngIf="authN.loginStrategy$ | async as loginStrategy">
    <button (click)="login(loginStrategy)" class="login-button" [disabled]="(authN.authNState$ | async) === 'authenticating'">
      <mat-spinner
        class="spinner"
        [diameter]="16"
        *ngIf="(authN.authNState$ | async) === 'authenticating'"
      ></mat-spinner>
      <mat-icon
        class="error-icon"
        *ngIf="(authN.authNState$ | async) === 'error'"
        color="warn"
        inline="true"
        [matTooltip]="(authN.errorMessage$ | async) ?? ''"
        >report</mat-icon
      >
      <div
        *ngIf="
          !['authenticating', 'error'].includes((authN.authNState$ | async) ?? '')
        "
      ></div>
      <span> login </span>
    </button>
  </ng-container>
  <div *ngIf="!authN"></div>
</ng-container>
