// libs/porrtal-components/r-quick-start-material/src/lib/account/account-detail/account-detail.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ViewComponentProps } from '@porrtal/r-api';
import { Fragment, useEffect, useState } from 'react';
import {
  Account,
  AccountData,
  fetchAccountData,
} from '../../data/account-data';
import styles from './account-detail.module.scss';
import Moment from 'moment';

export function AccountDetail(props: ViewComponentProps) {
  const [accountData, setAccountData] = useState<AccountData>();
  const [account, setAccount] = useState<Account | null | undefined>();
  useEffect(() => {
    fetchAccountData(0).then((d) => {
      setAccountData(d);
      const currentAccount = d?.find(
        (acct) => acct.accountId === props.viewState?.state?.['accountId']
      );
      setAccount(currentAccount ?? null);
    });
  }, [props.viewState]);

  if (account === undefined) {
    return <div>loading account data...</div>;
  }

  if (account === null) {
    return (
      <div>
        <span>accountId:&nbsp;</span>
        <span>{`${props.viewState?.state?.['accountId']}`}</span>
        <span>&nbsp;not found.</span>
      </div>
    );
  }

  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>
        {account?.name} ({account?.accountId}) - Account Detail
      </h3>
      <div className={styles['data-container']}>
        {account?.orders.map((order, index) => (
          <Fragment key={index}>
            <span>{order.item}</span>
            <span>
              {'$' +
                order.amount
                  .toFixed(0)
                  .replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')}
            </span>
            <span>{Moment(order.date).format('YYYY-DD-MM')}</span>
          </Fragment>
        ))}
      </div>
    </div>
  );
}

export default AccountDetail;

// libs/porrtal-components/a-quick-start-material/src/lib/account/account-detail/account-detail.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Moment from 'moment';
import { ViewState } from '@porrtal/a-api';
import { Account, accountData, AccountOrder } from '../../data/account-data';

@Component({
  selector: 'porrtal-account-detail',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './account-detail.component.html',
  styleUrls: ['./account-detail.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccountDetailComponent {
  private _viewState?: ViewState;
  @Input() set viewState(value: ViewState | undefined) {
    this._viewState = value;
    if (this._viewState?.state && this._viewState?.state['accountId']) {
      const accountId = this._viewState?.state['accountId'];
      this.account = accountData.find(
        (account) => account.accountId == accountId
      );
      this.orders = [];
      if (this.account) {
        this.orders = this.account.orders.map((order) => ({
          ...order,
          amountText:
            '$' +
            order.amount.toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,'),
        }));
      }
    }
  }
  get viewState() {
    return this._viewState;
  }

  public Moment = Moment;
  public account?: Account;
  public orders?: (AccountOrder & { amountText: string })[];
}

<div class="container">
  <h3 class="title">
    {{ account?.name }} ({{ account?.accountId }}) - Account Detail
  </h3>
  <div class="data-container">
    <ng-container *ngFor="let order of orders">
      <span>{{ order.item }}</span>
      <span>
        {{ order.amountText }}
      </span>
      <span>{{ Moment(order.date).format('YYYY-DD-MM') }}</span>
    </ng-container>
  </div>
</div>
