// libs/porrtal-components/quick-start-demo/src/lib/account/account-detail/account-detail.tsx
import { ViewComponentProps } from '@porrtal/api';
import { useEffect, useState } from 'react';
import {
  Account,
  AccountData,
  fetchAccountData,
} from '../../data/account-data';
import styles from './account-detail.module.scss';
import Moment from 'moment';

export function AccountDetail(props: ViewComponentProps) {
  const [accountData, setAccountData] = useState<AccountData>();
  const [account, setAccount] = useState<Account | null | undefined>();
  useEffect(() => {
    fetchAccountData(500).then((d) => {
      setAccountData(d);
      const currentAccount = d?.find(
        (acct) => acct.accountId === props.viewState?.state?.['accountId']
      );
      setAccount(currentAccount ?? null);
    });
  }, [props.viewState]);

  if (account === undefined) {
    return <div>loading account data...</div>;
  }

  if (account === null) {
    return (
      <div>
        <span>accountId:&nbsp;</span>
        <span>{`${props.viewState?.state?.['accountId']}`}</span>
        <span>&nbsp;not found.</span>
      </div>
    );
  }

  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>
        {account?.name} ({account?.accountId}) - Account Detail
      </h3>
      <div className={styles['data-container']}>
        {account?.orders.map(order => (
          <>
            <span>{order.item}</span>
            <span>{'$' + order.amount.toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')}</span>
            <span>{Moment(order.date).format('YYYY-DD-MM')}</span>
          </>
        ))}
      </div>
    </div>
  );
}

export default AccountDetail;

// libs/porrtal-components/a/quick-start-demo/src/lib/account/account-detail/account-detail.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Moment from 'moment';
import { ViewState } from '@porrtal/a-api';
import { Account, accountData, AccountOrder } from '../../data/account-data';

@Component({
  selector: 'porrtal-account-detail',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './account-detail.component.html',
  styleUrls: ['./account-detail.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccountDetailComponent {
  private _viewState?: ViewState;
  @Input() set viewState(value: ViewState | undefined) {
    this._viewState = value;
    if (this._viewState?.state && this._viewState?.state['accountId']) {
      const accountId = this._viewState?.state['accountId'];
      this.account = accountData.find(
        (account) => account.accountId === accountId
      );
      this.orders = [];
      if (this.account) {
        this.orders = this.account.orders.map((order) => ({
          ...order,
          amountText:
            '$' +
            order.amount.toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,'),
        }));
      }
    }
  }
  get viewState() {
    return this._viewState;
  }

  public Moment = Moment;
  public account?: Account;
  public orders?: (AccountOrder & { amountText: string })[];
}

<div class="container">
  <h3 class="title">
    {{ account?.name }} ({{ account?.accountId }}) - Account Detail
  </h3>
  <div class="data-container">
    <ng-container *ngFor="let order of orders">
      <span>{{ order.item }}</span>
      <span>
        {{order.amountText }}
      </span>
      <span>{{ Moment(order.date).format('YYYY-DD-MM') }}</span>
    </ng-container>
  </div>
</div>
