// apps/porrtal-auth/a-strapi-app/src/app/views/v2/v2.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-workspace-v2',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './v2.component.html',
  styleUrls: ['./v2.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class V2Component {}

// apps/porrtal-auth/n-msal-app/views/v2/v2.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './v2.module.scss';

/* eslint-disable-next-line */
export interface V2Props {}

export function V2(props: V2Props) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to V2!</h1>
    </div>
  );
}

export default V2;
