// libs/porrtal/a-shell-material/src/lib/view-stack/view-stack.component.ts
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  QueryList,
  ViewChild,
  ViewChildren,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Pane,
  paneTypes,
  paneArrangements,
  ViewState,
  PaneType,
  PaneArrangement,
  ViewLaunch,
} from '@porrtal/a-api';
import { MatTabsModule } from '@angular/material/tabs';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule, MatMenuTrigger } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { MatListModule } from '@angular/material/list';
import { MatCardModule } from '@angular/material/card';
import { ShellStateService, ViewHostComponent } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-view-stack',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatIconModule,
    MatMenuModule,
    MatDividerModule,
    MatListModule,
    MatCardModule,
    ViewHostComponent,
  ],
  templateUrl: './view-stack.component.html',
  styleUrls: ['./view-stack.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ViewStackComponent implements AfterContentChecked {
  _pane?: Pane;
  @Input() set pane(value: Pane | undefined) {
    this._pane = value;
    this.paneTypes = paneTypes.filter(
      (pt) => pt !== 'search' && pt !== (this._pane?.paneType ?? '')
    );
    const ii = this.pane?.viewStates.findIndex(
      (vs) => vs.key === this.pane?.currentKey
    );
    if (ii !== undefined) {
      this.selectedTabIndex = ii;
    }
  }
  get pane() {
    return this._pane;
  }

  @ViewChild(MatMenuTrigger, { static: true }) matMenuTrigger?: MatMenuTrigger;
  @ViewChildren('card', { read: ElementRef }) cards?: QueryList<
    ElementRef<HTMLElement>
  >;

  @ViewChildren(ViewHostComponent)
  portalViewHosts?: QueryList<ViewHostComponent>;

  public paneTypes?: string[];
  public selectedTabIndex?: number;
  public paneArrangements = paneArrangements;
  menuTopLeftPosition = { x: '0', y: '0' };
  public moveIcons: { [key: string]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  constructor(public shellStateService: ShellStateService) {
    const ii = this.pane?.viewStates.findIndex(
      (vs) => vs.key === this.pane?.currentKey
    );
  }

  ngAfterContentChecked(): void {
    if (this.cards && this.pane) {
      this.cards.some((card, ii) => {
        const isSelected =
          this.pane?.currentKey === this.pane?.viewStates[ii].key;
        if (isSelected) {
          card.nativeElement.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
          });
        }
        return isSelected;
      });
    }
  }

  doChangeTabIndex(ii: number) {
    if (this.pane) {
      this.shellStateService.dispatch({
        type: 'setCurrentViewStateByKey',
        key: this.pane.viewStates[ii].key,
        pane: this.pane,
      });
    }
  }

  doContextMenu(evt: MouseEvent, viewState: ViewState, ii: number): void {
    evt.preventDefault();
    evt.stopPropagation();

    // we record the mouse position in our object
    this.menuTopLeftPosition.x = evt.clientX + 'px';
    this.menuTopLeftPosition.y = evt.clientY + 'px';

    if (this.matMenuTrigger) {
      this.matMenuTrigger.menuData = { viewState, ii };
      this.matMenuTrigger.openMenu();
    }
  }

  doCloseTab(evt: MouseEvent, viewState: ViewState): void {
    this.shellStateService.dispatch({
      type: 'deleteViewState',
      key: viewState.key,
    });
  }

  doMoveTab(evt: MouseEvent, viewState: ViewState, toPaneType: string): void {
    this.shellStateService.dispatch({
      type: 'moveView',
      key: viewState.key,
      toPane: toPaneType as PaneType,
    });
  }

  doSetArrangementType(
    evt: MouseEvent,
    viewState: ViewState,
    paneArrangement: PaneArrangement
  ): void {
    if (this.pane) {
      this.shellStateService.dispatch({
        type: 'arrangePane',
        pane: this.pane,
        paneArrangement,
      });
    }
  }

  doLaunch(viewLaunch: ViewLaunch) {
    console.log('launch info', viewLaunch);
    this.shellStateService.dispatch({
      type: 'launchView',
      viewId: viewLaunch.viewId,
      state: viewLaunch.state,
    });
  }

  doMaximizeTab(evt: MouseEvent, viewState: ViewState, ii: number) {
    this.portalViewHosts?.toArray()[ii].maximize();
  }
}

<ng-container [ngSwitch]="pane?.arrange ?? 'tabs-top'">
  <!-- tabs-top -->
  <mat-tab-group
    mat-stretch-tabs="false"
    mat-align-tabs="start"
    preserveContent
    *ngSwitchCase="'tabs-top'"
    (selectedIndexChange)="doChangeTabIndex($event)"
    [selectedIndex]="selectedTabIndex"
  >
    <mat-tab *ngFor="let viewState of pane?.viewStates; let ii = index">
      <ng-template mat-tab-label>
        <mat-icon
          (contextmenu)="doContextMenu($event, viewState, ii)"
          class="tab-icon"
          >{{ viewState.displayIcon }}</mat-icon
        >
        <mat-icon
          (contextmenu)="doContextMenu($event, viewState, ii)"
          (click)="doMaximizeTab($event, viewState, ii)"
          class="tab-icon"
          >north_east</mat-icon
        >
        <span (contextmenu)="doContextMenu($event, viewState, ii)">{{
          viewState.displayText
        }}</span>
        <mat-icon
          (click)="doCloseTab($event, viewState)"
          inline="true"
          class="close-icon"
          >close</mat-icon
        >
      </ng-template>
      <porrtal-view-host
        #porrtalViewHost
        [viewState]="viewState"
      ></porrtal-view-host>
    </mat-tab>
  </mat-tab-group>

  <!-- tabs-left -->
  <div class="vertical-tabs-container" *ngSwitchCase="'tabs-left'">
    <div class="vertical-tabs-tabs-container">
      <div class="vertical-tabs-nav-list">
        <mat-nav-list>
          <mat-list-item
            *ngFor="let viewState of pane?.viewStates; let ii = index"
            [ngClass]="{ selected: viewState.key === pane?.currentKey }"
            (click)="doChangeTabIndex(ii)"
            (contextmenu)="doContextMenu($event, viewState, ii)"
          >
            <a
              *ngIf="pane?.paneType === 'nav'"
              tabindex="0"
              class="vertical-tabs-anchor"
              (click)="
                shellStateService.dispatch({
                  type: 'toggleNav',
                  item: viewState
                })
              "
            >
              <div>
                <mat-icon>{{ viewState.displayIcon }}</mat-icon>
              </div>
            </a>
            <a
              *ngIf="pane?.paneType !== 'nav'"
              tabindex="0"
              class="vertical-tabs-anchor"
            >
              <div>
                <mat-icon>{{ viewState.displayIcon }}</mat-icon>
              </div>
            </a>
          </mat-list-item>
        </mat-nav-list>
      </div>
    </div>
    <div class="vertical-tabs-content">
      <div style="position: relative; height: 100%">
        <div
          class="vertical-tabs-view-host-container"
          *ngFor="let viewState of pane?.viewStates; let ii = index"
          [style.zIndex]="viewState.key === pane?.currentKey ? 10 : 0"
        >
          <porrtal-view-host
            #porrtalViewHost
            [viewState]="viewState"
          ></porrtal-view-host>
        </div>
        <div class="vertical-tabs-content-background-div"></div>
      </div>
    </div>
  </div>

  <!-- cards -->
  <div *ngSwitchCase="'cards'" class="card-container">
    <div class="cards">
      <mat-card
        #card
        *ngFor="let viewState of pane?.viewStates; let ii = index"
        class="card"
      >
        <mat-card-title style="margin: 0">
          <div
            class="card-title"
            [ngClass]="{
              'selected-card-title': viewState.key === pane?.currentKey
            }"
            (click)="doChangeTabIndex(ii)"
            (contextmenu)="doContextMenu($event, viewState, ii)"
          >
            <mat-icon class="tab-icon">{{ viewState.displayIcon }}</mat-icon>
            <mat-icon
              (click)="doMaximizeTab($event, viewState, ii)"
              class="tab-icon"
              >north_east</mat-icon
            >
            <span>{{ viewState.displayText }}</span>
            <mat-icon
              (click)="doCloseTab($event, viewState)"
              inline="true"
              class="close-icon"
              >close</mat-icon
            >
          </div>
        </mat-card-title>
        <mat-card-content>
          <div class="view-host-container">
            <porrtal-view-host
              #porrtalViewHost
              [viewState]="viewState"
            ></porrtal-view-host>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</ng-container>

<!-- an hidden div is created to set the position of appearance of the menu-->
<div
  style="visibility: hidden; position: fixed"
  [style.left]="menuTopLeftPosition.x"
  [style.top]="menuTopLeftPosition.y"
  [matMenuTriggerFor]="rightMenu"
></div>

<!-- standard material menu -->
<mat-menu #rightMenu="matMenu">
  <ng-template matMenuContent let-viewState="viewState" let-ii="ii">
    <button mat-menu-item (click)="doMaximizeTab($event, viewState, ii)">
      <span>
        <mat-icon inline="true" class="menu-close-icon">north_east</mat-icon>
        <span>Maximize Tab</span>
      </span>
    </button>
    <mat-divider></mat-divider>
    <button mat-menu-item (click)="doCloseTab($event, viewState)">
      <span>
        <mat-icon inline="true" class="menu-close-icon">close</mat-icon>
        <span>Close Tab</span>
      </span>
    </button>
    <mat-divider></mat-divider>
    <button
      *ngIf="
        viewState?.userInfo &&
          viewState?.userInfo.length > 0 &&
          shellStateService.select('showUserInfo') | async
      "
      mat-menu-item
      [matMenuTriggerFor]="info"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon material-icons-outlined"
          >info</mat-icon
        >
        <span>Info...</span>
      </span>
    </button>
    <button
      *ngIf="
        viewState?.devInfo &&
          viewState?.devInfo.length > 0 &&
          shellStateService.select('showDevInfo') | async
      "
      mat-menu-item
      [matMenuTriggerFor]="devInfo"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon material-icons-outlined"
          >build</mat-icon
        >
        <span>Dev Info...</span>
      </span>
    </button>
    <button
      mat-menu-item
      class="menu-button"
      [matMenuTriggerFor]="arrangeOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon"
          >pivot_table_chart</mat-icon
        >
        <span>Arrange...</span>
      </span>
    </button>
    <button
      mat-menu-item
      [matMenuTriggerFor]="moveOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">open_with</mat-icon>
        <span>Move To...</span>
      </span>
    </button>
    <button
      mat-menu-item
      (click)="
        shellStateService.dispatch({
          type: 'copyToClipboard',
          viewState: this.viewState
        })
      "
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">content_copy</mat-icon>
        <span>Copy link</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #info="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doLaunch(viewLaunch)"
      mat-menu-item
      *ngFor="let viewLaunch of viewState.userInfo"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-close-icon material-icons-outlined"
          >{{ viewLaunch.state['displayIcon'] }}</mat-icon
        >
        <span>{{ viewLaunch.state['displayText'] }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #devInfo="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doLaunch(viewLaunch)"
      mat-menu-item
      *ngFor="let viewLaunch of viewState.devInfo"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-close-icon material-icons-outlined"
          >{{ viewLaunch.state['displayIcon'] }}</mat-icon
        >
        <span>{{ viewLaunch.state['displayText'] }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #arrangeOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      mat-menu-item
      (click)="doSetArrangementType($event, viewState, paneArrangement)"
      *ngFor="let paneArrangement of paneArrangements"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">{{
          pane?.arrange === paneArrangement ? 'done' : ''
        }}</mat-icon>
        <span>{{ paneArrangement }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #moveOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doMoveTab($event, viewState, paneType)"
      mat-menu-item
      *ngFor="let paneType of paneTypes"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-move-to-icon material-icons-outlined"
          >{{ moveIcons[paneType] }}</mat-icon
        >
        <span>{{ paneType }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

// libs/porrtal/r-shell-blueprint/src/lib/view-stack/view-stack.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './view-stack.module.scss';
import {
  Tab,
  Tabs,
  Icon,
  Menu,
  MenuItem,
  MenuDivider,
  Card,
  Button,
  IconName,
} from '@blueprintjs/core';
import { Dispatch, useEffect } from 'react';
import {
  ShellAction,
  useShellDispatch,
  ViewHost,
  ViewStackProps,
} from '@porrtal/r-shell';
import { ContextMenu2, Tooltip2 } from '@blueprintjs/popover2';
import {
  paneArrangements,
  PaneType,
  paneTypes,
  ViewState,
} from '@porrtal/r-api';

export function ViewStack(props: ViewStackProps) {
  const dispatch = useShellDispatch();
  useEffect(() => {
    if (!props.pane.currentKey && props?.pane?.viewStates?.length && dispatch) {
      dispatch({
        type: 'setCurrentViewStateByKey',
        pane: props.pane,
        key: props.pane.viewStates[0].key,
      });
    }
  }, [props.pane, dispatch]);

  switch (props.pane.arrange) {
    case 'tabs-top':
      return (
        <ViewStackTabsTop
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          dispatch={dispatch}
          onClose={props.onClose}
        />
      );

    case 'tabs-left':
      return (
        <ViewStackTabsLeft
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          dispatch={dispatch}
          onClose={props.onClose}
        />
      );

    case 'cards':
      return (
        <ViewStackCards
          pane={props.pane}
          showUserInfo={props.showUserInfo}
          showDevInfo={props.showDevInfo}
          dispatch={dispatch}
        />
      );
  }

  return (
    <div>ViewStack Arrangement ('{props.pane.arrange}') Not Supported.</div>
  );
}

function ViewStackTabsTop(
  props: ViewStackProps & { dispatch: Dispatch<ShellAction> }
) {
  return (
    <Tabs
      animate={true}
      id="ViewStack"
      key={'horizontal'}
      renderActiveTabPanelOnly={false}
      vertical={false}
      onChange={(evt) =>
        props.dispatch({
          type: 'setCurrentViewStateByKey',
          pane: props.pane,
          key: evt.toLocaleString(),
        })
      }
      selectedTabId={props.pane.currentKey}
      className={`${styles['tabs']} ${styles['tabs-top']}`}
    >
      {props.pane.viewStates.map((item) => (
        <Tab
          id={item.key}
          key={item.key}
          title={
            <ViewStackContextMenu
              pane={props.pane}
              showUserInfo={props.showUserInfo}
              showDevInfo={props.showDevInfo}
              dispatch={props.dispatch}
              item={item}
            ></ViewStackContextMenu>
          }
          panel={
            <div className={styles['viewHostContainer']}>
              <ViewHost key={item.key} viewState={item}></ViewHost>
            </div>
          }
          className={styles['tab']}
        />
      ))}
      {props.onClose && (
        <>
          <Tabs.Expander />
          <Button
            onClick={(evt) => (props.onClose ? props.onClose(evt) : null)}
          >
            <Icon icon="cross" />
            <span>close</span>
          </Button>
        </>
      )}
    </Tabs>
  );
}

function ViewStackTabsLeft(
  props: ViewStackProps & { dispatch: Dispatch<ShellAction> }
) {
  return (
    <Tabs
      animate={true}
      id="ViewStack"
      key={'horizontal'}
      renderActiveTabPanelOnly={false}
      vertical={true}
      onChange={(evt) =>
        props.dispatch({
          type: 'setCurrentViewStateByKey',
          pane: props.pane,
          key: evt.toLocaleString(),
        })
      }
      selectedTabId={props.pane.currentKey}
      className={`${styles['tabs']} ${styles['tabs-left']}`}
    >
      {props.pane.viewStates.map((item) => (
        <Tab
          id={item.key}
          key={item.key}
          title={
            <ViewStackContextMenu
              pane={props.pane}
              showUserInfo={props.showUserInfo}
              showDevInfo={props.showDevInfo}
              dispatch={props.dispatch}
              item={item}
            ></ViewStackContextMenu>
          }
          panel={
            <div className={styles['viewHostContainer']}>
              <ViewHost key={item.key} viewState={item}></ViewHost>
            </div>
          }
          className={styles['tab']}
        />
      ))}
      {props.onClose && (
        <>
          <Tabs.Expander />
          <Button
            onClick={(evt) => (props.onClose ? props.onClose(evt) : null)}
          >
            <Icon icon="cross" />
          </Button>
        </>
      )}
    </Tabs>
  );
}

function ViewStackCards(
  props: ViewStackProps & { dispatch: Dispatch<ShellAction> }
) {
  return (
    <div className={styles['card-container']}>
      <div className={styles['cards']}>
        {props.pane.viewStates.map((item) => (
          <Card id={item.key} key={item.key} className={`${styles['card']}`}>
            <Button
              className={
                item.key === props.pane.currentKey
                  ? styles['selected-card-button']
                  : ''
              }
              onClick={(evt) =>
                props.dispatch({
                  type: 'setCurrentViewStateByKey',
                  pane: props.pane,
                  key: item.key,
                })
              }
            >
              <ViewStackContextMenu
                pane={props.pane}
                showUserInfo={props.showUserInfo}
                showDevInfo={props.showDevInfo}
                dispatch={props.dispatch}
                item={item}
              ></ViewStackContextMenu>
            </Button>
            <div className={styles['viewHostContainer']}>
              <ViewHost key={item.key} viewState={item}></ViewHost>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}

export default ViewStack;

function ViewStackContextMenu(
  props: ViewStackProps & { dispatch: Dispatch<ShellAction> } & {
    item: ViewState;
  }
) {
  const moveIcons: { [key in PaneType]: string } = {
    nav: 'arrow-left',
    main: 'arrow-up',
    bottom: 'arrow-down',
    right: 'arrow-right',
    search: 'clear',
  };

  return (
    <ContextMenu2
      content={
        <Menu>
          {props.pane.paneType !== 'search' && (
            <MenuItem
              key={`close`}
              icon={'cross'}
              text={`close tab`}
              onClick={(evt) => {
                props.dispatch({
                  type: 'deleteViewState',
                  key: props.item.key,
                });
                evt.stopPropagation();
              }}
            />
          )}
          {props.pane.paneType !== 'search' && <MenuDivider />}
          {props.showUserInfo &&
            props.item?.userInfo &&
            props.item?.userInfo.length > 0 && (
              <MenuItem key={'userInfo'} text="Info..." icon="info-sign">
                {props.item.userInfo.map((info) => (
                  <MenuItem
                    key={
                      props.item.key +
                      (info?.state ? info?.state['displayText'] : '')
                    }
                    icon={
                      info?.state
                        ? (info.state['displayIcon'] as IconName)
                        : 'help'
                    }
                    text={
                      info?.state
                        ? (info.state['displayText'] as string)
                        : 'help'
                    }
                    onClick={(evt) => {
                      props.dispatch({
                        type: 'launchView',
                        viewId: info.viewId,
                        state: info.state,
                      });
                    }}
                  ></MenuItem>
                ))}
              </MenuItem>
            )}
          {props.showDevInfo &&
            props.item?.devInfo &&
            props.item?.devInfo.length > 0 && (
              <MenuItem key={'devInfo'} text="dev Info..." icon="wrench">
                {props.item.devInfo.map((info) => (
                  <MenuItem
                    key={
                      props.item.key +
                      (info?.state ? info?.state['displayText'] : '')
                    }
                    icon={
                      info?.state
                        ? (info.state['displayIcon'] as IconName)
                        : 'help'
                    }
                    text={
                      info?.state
                        ? (info.state['displayText'] as string)
                        : 'help'
                    }
                    onClick={(evt) => {
                      props.dispatch({
                        type: 'launchView',
                        viewId: info.viewId,
                        state: info.state,
                      });
                    }}
                  ></MenuItem>
                ))}
              </MenuItem>
            )}
          {((props.showUserInfo &&
            props.item?.userInfo &&
            props.item?.userInfo.length > 0) ||
            (props.showUserInfo &&
              props.item?.userInfo &&
              props.item?.userInfo.length > 0)) && <MenuDivider />}
          <MenuItem
            key={'arrange'}
            text="Arrange tabs..."
            icon="column-layout"
            intent="primary"
          >
            {paneArrangements.map((paneArrangement) => (
              <MenuItem
                key={`arrange-${paneArrangement}`}
                icon={
                  (props.pane.arrange === paneArrangement
                    ? 'tick'
                    : '') as IconName
                }
                text={`${paneArrangement}`}
                onClick={() =>
                  props.dispatch({
                    type: 'arrangePane',
                    pane: props.pane,
                    paneArrangement,
                  })
                }
              />
            ))}
          </MenuItem>
          {props.pane.paneType !== 'search' && (
            <MenuItem
              key={'move'}
              text="Move to..."
              icon="move"
              intent="primary"
            >
              {paneTypes
                .filter(
                  (paneType) =>
                    paneType !== 'search' && paneType !== props.pane.paneType
                )
                .map((paneType) => (
                  <MenuItem
                    key={`move-to-${paneType}`}
                    icon={moveIcons[paneType] as IconName}
                    text={`${paneType} pane`}
                    onClick={(evt) => {
                      props.dispatch({
                        type: 'moveView',
                        key: props.item.key,
                        toPane: paneType,
                      });
                    }}
                  />
                ))}
            </MenuItem>
          )}
        </Menu>
      }
    >
      {props.pane.arrange !== 'tabs-left' && (
        <span>
          {props.item.displayIcon && (
            <Icon
              style={{ marginLeft: '3px', marginRight: '3px' }}
              icon={props.item.displayIcon as IconName}
            />
          )}
          <span>{props.item.displayText}</span>
          {props.pane.paneType !== 'search' && (
            <Icon
              style={{ marginLeft: '5px' }}
              icon="cross"
              onClick={(evt) => {
                props.dispatch({
                  type: 'deleteViewState',
                  key: props.item.key,
                });
                evt.stopPropagation();
              }}
            />
          )}
        </span>
      )}
      {props.pane.arrange === 'tabs-left' && props.pane.paneType === 'nav' && (
        <Tooltip2 content={props.item.displayText}>
          <span
            onClick={(evt) => {
              props.dispatch({
                type: 'toggleNav',
                item: props.item
              });
            }}
          >
            <Icon icon={props.item.displayIcon as IconName} />
          </span>
        </Tooltip2>
      )}
      {props.pane.arrange === 'tabs-left' && props.pane.paneType !== 'nav' && (
        <Tooltip2 content={props.item.displayText}>
          <span>
            <Icon icon={props.item.displayIcon as IconName} />
          </span>
        </Tooltip2>
      )}
    </ContextMenu2>
  );
}
