// libs/porrtal/r-shell-material/src/lib/search/search.tsx
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Box, ClickAwayListener, Popper } from '@mui/material';
import {
  SearchProps,
  useIsSearchDialogOpen,
  useSearchAction,
  useShellComponents,
} from '@porrtal/r-shell';
import { useEffect, useRef, useState } from 'react';
import SearchInput, { SearchInputRef } from '../search-input/search-input';
import { SearchViewStack } from '@porrtal/r-shell';
import styles from './search.module.scss';

export function Search(props: SearchProps) {
  const shellComponents = useShellComponents();
  const searchInputRef = useRef<SearchInputRef>();
  const searchAction = useSearchAction();
  const [bodyElement, setBodyElement] = useState<HTMLElement>();
  const isSearchDialogOpen = useIsSearchDialogOpen();
  useEffect(() => {
    setBodyElement(document.body);
  }, [isSearchDialogOpen]);

  if (shellComponents && typeof window !== 'undefined' && window) {
    return (
      <>
        <SearchInput ref={searchInputRef}></SearchInput>
        <ClickAwayListener
          onClickAway={(evt) => searchAction.closeSearchDialog()}
        >
          <Popper
            nonce={'1'}
            onResize={() => {
              // do nothing
            }}
            onResizeCapture={() => {
              // do nothing
            }}
            className={styles['search-popper']}
            open={isSearchDialogOpen}
            onLoad={(evt) =>
              searchInputRef.current
                ? searchInputRef.current.input?.focus()
                : null
            }
            anchorEl={searchInputRef.current?.div}
            placement={'left'}
          >
            <Box sx={{ border: 1, p: 1, bgcolor: 'background.paper' }}>
              <SearchViewStack
                width={
                  searchInputRef.current && searchInputRef.current.div
                    ? `${searchInputRef.current.div.offsetLeft - 50}px`
                    : '700px'
                }
                height={
                  bodyElement ? `${bodyElement.offsetHeight - 50}px` : '700px'
                }
              ></SearchViewStack>
            </Box>
          </Popper>
        </ClickAwayListener>
      </>
    );
  } else {
    return <div></div>;
  }
}

export default Search;

// libs/porrtal/a-shell-material/src/lib/search/search.component.ts
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Inject,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import { CommonModule, DOCUMENT } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import {
  MatFormFieldModule,
  MAT_FORM_FIELD_DEFAULT_OPTIONS,
} from '@angular/material/form-field';
import { SearchStateService } from '@porrtal/a-shell';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { SearchDialogComponent } from '../search-dialog/search-dialog.component';
import {
  NgxPopperjsModule,
  NgxPopperjsContentComponent,
  NgxPopperjsPlacements,
} from 'ngx-popperjs';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'porrtal-search',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    NgxPopperjsModule,
    SearchDialogComponent,
  ],
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: MAT_FORM_FIELD_DEFAULT_OPTIONS,
      useValue: { subscriptSizing: 'dynamic' },
    },
  ],
})
export class SearchComponent implements OnDestroy {
  @ViewChild('searchInput', { read: ElementRef }) searchInput?: HTMLElement;
  @ViewChild('searchDialog', { read: NgxPopperjsContentComponent })
  searchDialog?: NgxPopperjsContentComponent;

  public popperPlacement = NgxPopperjsPlacements.LEFTEND;
  public width = '500px';
  public height = '300px';
  private destroySubject = new Subject<boolean>();

  constructor(
    public searchStateService: SearchStateService,
    private dialog: MatDialog,
    @Inject(DOCUMENT) public document: Document,
    private el: ElementRef<HTMLElement>
  ) {
    this.searchStateService
      .select('isSearchDialogOpen')
      .pipe(takeUntil(this.destroySubject))
      .subscribe((isSearchDialogOpen: boolean) => {
        if (isSearchDialogOpen) {
          this.showSearch();
        } else {
          this.hideSearch();
        }
      });
  }

  hideSearch() {
    if (this.searchDialog) {
      this.searchDialog.hide();
    }
  }

  showSearch() {
    this.width = `${this.el.nativeElement.offsetLeft - 50}px`;
    this.height = `${this.document.body.offsetHeight - 50}px`;

    if (this.searchDialog) {
      this.searchDialog.show();
    }
  }

  doSearchTextChanged(evt: Event) {
    this.searchStateService.dispatch({
      type: 'setSearchText',
      searchText: (evt.target as HTMLInputElement).value,
    });
    this.searchStateService.dispatch({
      type: 'openSearchDialog',
    });
  }

  doHidePopper() {
    this.searchStateService.dispatch({
      type: 'closeSearchDialog',
    });
  }

  doShowPopper() {
    this.searchStateService.dispatch({
      type: 'openSearchDialog',
    });
  }

  ngOnDestroy(): void {
    this.destroySubject.next(true);
    this.destroySubject.complete();
  }
}

<div class="search-container">
  <mat-form-field class="search-form-field" appearance="fill">
    <mat-icon
      style="font-size: 24px; height: 24px; width: 24px; padding: 0px;"
      matPrefix
      [popper]="searchDialog"
      [popperApplyClass]="'search-popper'"
      [popperPlacement]="popperPlacement"
      [popperPositionFixed]="true"
      (popperOnHidden)="doHidePopper()"
      (popperOnShown)="doShowPopper()"
      >search</mat-icon
    >
    <input
      #searchInput
      type="text"
      matInput
      (keyup)="doSearchTextChanged($event)"
    />
  </mat-form-field>
</div>
<popper-content #searchDialog>
  <div [style.width]="width" [style.height]="height">
    <porrtal-search-dialog></porrtal-search-dialog>
  </div>
</popper-content>
