// libs/porrtal/shell-blueprint/src/lib/logger-messages/logger-messages.tsx
import { ViewComponentProps, LoggerEntry } from '@porrtal/api';
import { useLoggerState } from '@porrtal/shell';
import styles from './logger-messages.module.scss';
import { AgGridReact } from 'ag-grid-react';
import { ColDef } from 'ag-grid-community';
import { useState } from 'react';

import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-balham.css';

export function LoggerMessages(props: ViewComponentProps) {
  const loggerState = useLoggerState();
  const [columnDefs, setColumnDefs] = useState<ColDef<LoggerEntry>[]>([
    { field: 'message',  },
    { field: 'system' },
    { field: 'subsystem' },
    { field: 'component' },
    { field: 'severity' },
    { field: 'consumer' },
    { field: 'messageDetail' },
    { field: 'isRead',  },
    { field: 'user',  },
  ]);
  const [defaultColumnDef, setDefaultColumnDef] = useState<ColDef<LoggerEntry>>({
    sortable: true,
    filter: true,
    resizable: true
  });
  return (
    <div className={styles['container']}>
      <span>Logger Entries:</span>
      <div className={`${styles['grid-container']} ag-theme-balham`}>
        <AgGridReact<LoggerEntry>
          rowData={loggerState.entries}
          columnDefs={columnDefs}
          defaultColDef={defaultColumnDef}
        ></AgGridReact>
      </div>
    </div>
  );
}

export default LoggerMessages;

// libs/porrtal/a/shell-material/src/lib/logger-messages/logger-messages.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoggerStateService } from '@porrtal/a-shell';
import { LoggerEntry } from '@porrtal/a-api';
import { Observable } from 'rxjs';
import { AgGridModule } from 'ag-grid-angular';
import { ColDef } from 'ag-grid-community';

@Component({
  selector: 'porrtal-logger-messages',
  standalone: true,
  imports: [CommonModule, AgGridModule],
  templateUrl: './logger-messages.component.html',
  styleUrls: ['./logger-messages.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoggerMessagesComponent {

  public entries$: Observable<LoggerEntry[]>

  public columnDefs: ColDef<LoggerEntry>[] = [
    { field: 'message' },
    { field: 'system' },
    { field: 'subsystem' },
    { field: 'component' },
    { field: 'severity' },
    { field: 'consumer' },
    { field: 'messageDetail' },
    { field: 'isRead' },
    { field: 'user' },
  ];

  public defaultColumnDef: ColDef<LoggerEntry> = {
    sortable: true,
    filter: true,
    resizable: true,
}

  constructor(private loggerStateService: LoggerStateService) {
    this.entries$ = this.loggerStateService.select('entries');
  }
}

<!-- <pre>{{ entries$ | async | json }}</pre> -->
<div class="container">
  <span>Logger Entries:</span>
  <div class="grid-container">
    <ag-grid-angular
      class="ag-theme-balham"
      [rowData]="entries$ | async"
      [columnDefs]="columnDefs"
    >
    </ag-grid-angular>
  </div>
</div>
