// libs/porrtal/r-shell-blueprint/src/lib/shell-state-dashboard/auth-z-card/auth-z-card.tsx
/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './auth-z-card.module.scss';
import {
  CardContainerProps,
  useShellDispatch,
  useShellState,
} from '@porrtal/r-shell';
import { Icon } from '@blueprintjs/core';
import { useRef, useState } from 'react';

export function AuthZCard(props: CardContainerProps) {
  const shellState = useShellState();
  const shellDispatch = useShellDispatch();
  const cardRef = useRef<HTMLDivElement>(null);
  const [isMaximized, setIsMaximized] = useState(false);

  return (
    <div ref={cardRef} className={styles['card-layout']}>
      {!isMaximized && (
        <div className={styles['card-header']}>
          <span>auth-z</span>
          <Icon
            icon="arrow-top-right"
            onClick={() => {
              if (cardRef.current) {
                shellDispatch({
                  type: 'maximize',
                  htmlEl: cardRef.current,
                  maximizeText: `auth z: ${
                    (props.card.data as { name: string }).name
                  }`,
                  restore: () => setIsMaximized(false),
                });
                setIsMaximized(true);
              }
            }}
          ></Icon>
        </div>
      )}
      <div className={styles['card-content-container']}>
        <div className={styles['pane-header']}>
          {(props.card.data as { name: string }).name}
        </div>
        <pre>{JSON.stringify(props.card.data, null, 2)}</pre>
        <hr />
        <pre>
          {JSON.stringify(
            shellState.authZs[(props.card.data as { name: string }).name],
            null,
            2
          )}
        </pre>
      </div>
    </div>
  );
}

export default AuthZCard;

// libs/porrtal/a-shell-material/src/lib/shell-state-dashboard/auth-z-card/auth-z-card.component.ts
﻿/*
Copyright 2024 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { BehaviorSubject, combineLatest, map, Observable } from 'rxjs';
import { AuthZ, StateObject } from '@porrtal/a-api';
import { AuthZProviderInterface, AuthZProviderState } from '@porrtal/a-user';
import { ShellStateService } from '@porrtal/a-shell';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'porrtal-auth-z-card',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatIconModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatCardModule,
  ],
  templateUrl: './auth-z-card.component.html',
  styleUrls: ['./auth-z-card.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AuthZCardComponent {
  isMaximized$ = new BehaviorSubject<boolean>(false);
  // childIndex = -1;
  // parentNativeEl: any;
  props?: StateObject;

  authZSubj = new BehaviorSubject<{
    authZ: AuthZProviderInterface | undefined;
  }>({
    authZ: undefined,
  });

  authZShell$: Observable<AuthZ | undefined>;

  @Input() public set data(value: AuthZProviderInterface) {
    this.authZSubj.next({ authZ: value });
  }

  constructor(
    private readonly el: ElementRef,
    private shellStateService: ShellStateService
  ) {
    this.authZShell$ = combineLatest([shellStateService.select('authZs'), this.authZSubj], (authZs, authZ) => {
      if (!authZs || !authZ || !authZ.authZ?.getAuthZProviderInfo()?.name) {
        return undefined;
      }

      return authZs[authZ.authZ?.getAuthZProviderInfo()?.name];
    });
  }

  toggleMax() {
    this.shellStateService.dispatch({
      type: 'maximize',
      htmlEl: this.el.nativeElement,
      maximizeText: 'auth z',
      restore: () => {
        this.isMaximized$.next(false);
        console.log('auth-z-card restore', this);
      },
    });

    this.isMaximized$.next(true);
  }
}

<mat-card class="container-container" [class.maximize]="isMaximized$ | async">
  <div class="container">
    <mat-toolbar
      class="toolbar"
      [color]="
        (((authZSubj | async)?.authZ?.authZProviderState$ | async) ?? '') ===
        'error'
          ? 'warn'
          : (((authZSubj | async)?.authZ?.authZProviderState$ | async) ??
              '') ===
              '' ||
            (((authZSubj | async)?.authZ?.authZProviderState$ | async) ??
              '') ===
              'init'
          ? ''
          : 'accent'
      "
    >
      <!-- key icon -->
      <span class="status-icon">
        <mat-icon>lock</mat-icon>
      </span>

      <!-- card status-->
      <mat-spinner
        class="spinner"
        [diameter]="16"
        *ngIf="(((authZSubj | async)?.authZ?.authZProviderState$ | async) ?? '') === 'init'"
      ></mat-spinner>
      <span *ngIf="(((authZSubj | async)?.authZ?.authZProviderState$ | async) ?? '') === 'error'" class="status-icon">
        <mat-icon>warning</mat-icon>
      </span>
      <span *ngIf="(((authZSubj | async)?.authZ?.authZProviderState$ | async) ?? '') === ''" class="status-icon">
        <mat-icon>radio_button_unchecked</mat-icon>
      </span>
      <span *ngIf="(((authZSubj | async)?.authZ?.authZProviderState$ | async) ?? '') === 'ready'" class="status-icon">
        <mat-icon>task_alt</mat-icon>
      </span>

      <!-- card type -->
      <span class="card-type">auth z</span>

      <!-- card message -->
      <span *ngIf="authZSubj | async as auth">
        {{ auth?.authZ?.name$ | async }}
      </span>
      <span *ngIf="!(authZSubj | async)"></span>

      <!-- card maximize button -->
      <button
        *ngIf="!(isMaximized$ | async)"
        mat-button
        (click)="toggleMax()"
        class="maximize-button"
      >
        <mat-icon class="maximize-icon">north_east</mat-icon>
      </button>
    </mat-toolbar>

    <div class="card-content-container">
      <!-- authZProvider info -->
      <div
        *ngIf="(authZSubj | async)?.authZ as authZProvider"
        class="properties-container"
      >
        <!-- state -->
        <span class="property-title">state:</span>
        <span>{{ authZProvider.authZProviderState$ | async }}</span>

        <!-- error message -->
        <span
          *ngIf="
            (authZProvider.authZProviderState$ | async) === 'error' &&
            (authZProvider.errorMessage$ | async)?.message
          "
          class="property-title"
          >error message:</span
        >
        <span
          *ngIf="
            (authZProvider.authZProviderState$ | async) === 'error' &&
            (authZProvider.errorMessage$ | async)?.message
          "
          >{{ (authZProvider.errorMessage$ | async)?.message }}</span
        >

        <!-- warning message -->
        <span
          *ngIf="
            (authZProvider.authZProviderState$ | async) !== '' &&
            (authZProvider.warningMessage$ | async)?.message
          "
          class="property-title"
          >warning message:</span
        >
        <span
          *ngIf="
            (authZProvider.authZProviderState$ | async) !== '' &&
            (authZProvider.warningMessage$ | async)?.message
          "
          >{{ (authZProvider.warningMessage$ | async)?.message }}</span
        >

        <!-- roles -->
        <span
          *ngIf="(authZProvider.roles$ | async)?.length ?? 0 > 0"
          class="property-title"
          >roles:</span
        >
        <div *ngIf="(authZProvider.roles$ | async)?.length ?? 0 > 0">
          <div *ngFor="let role of (authZProvider.roles$ | async) ?? []">
            {{ role }}
          </div>
        </div>

        <!-- scopes -->
        <span
          *ngIf="(authZProvider.scopes$ | async)?.length ?? 0 > 0"
          class="property-title"
          >scopes:</span
        >
        <div *ngIf="(authZProvider.scopes$ | async)?.length ?? 0 > 0">
          <div *ngFor="let scope of (authZProvider.scopes$ | async) ?? []">
            {{ scope }}
          </div>
        </div>

        <!-- init function -->
        <span class="property-title">defined functions:</span>
        <div>
          <div *ngIf="authZProvider.init">init()</div>
        </div>
      </div>

      <!-- shell AuthZ Info -->
      <hr />
      <div *ngIf="authZSubj | async as authZ" class="properties-container">
        <!-- authZ.ready -->
        <span class="property-title">ready:</span>
        <span>{{ (authZShell$ | async)?.ready ?? false }}</span>

        <!-- authZ.checkPermission -->
        <span class="property-title">checkPermission():</span>
        <span>{{
          (authZShell$ | async)?.checkPermission ?? false ? 'defined' : 'not defined'
        }}</span>
      </div>
      <div *ngIf="authZShell$ | async as authZShell">
        <span class="property-title">authZ:</span>
        <pre><p>{{ authZShell | json }}</p></pre>
      </div>
      <div *ngIf="authZShell$ | async as authZ">
        <div class="property-title">
          launchQ({{ authZ?.launchQ?.length ?? 'undefined' }}):
        </div>
        <div *ngFor="let launchItem of authZ?.launchQ ?? []">
          {{ launchItem.viewId }}
        </div>
      </div>
      <div *ngIf="authZShell$ | async as authZ">
        <div class="property-title">
          noPermissionsQ({{ authZ?.noPermissionsQ?.length ?? 'undefined' }}):
        </div>
        <div *ngFor="let launchItem of authZ?.noPermissionsQ ?? []">
          {{ launchItem.viewId }}
        </div>
      </div>
      <div *ngIf="!(authZShell$ | async)">No AuthZ Info from Shell.</div>

      <!-- authZProvider info -->
      <ng-container *ngIf="(authZSubj | async)?.authZ as authZ">
        <hr />
        <!-- props -->
        <div *ngIf="authZ.props$ | async as props">
          <span class="property-title">props:</span>
          <pre><p>{{ props | json }}</p></pre>
        </div>
      </ng-container>

      <!-- login strategy -->
      <!-- <span class="property-title">login strategy:</span>
          <span>{{ authN.loginStrategy$ | async }}</span>
  
          <hr />
          <hr /> -->

      <!-- has any functions -->
      <!-- <span
            *ngIf="
              authN.init ||
              authN.loginWithRedirect ||
              authN.login ||
              authN.register ||
              authN.logout
            "
            class="property-title"
            >defined functions:</span
          >
          <span
            *ngIf="
              authN.init ||
              authN.loginWithRedirect ||
              authN.login ||
              authN.register ||
              authN.logout
            "></span> -->

      <!-- has init -->
      <!-- <span *ngIf="authN.init"></span>
          <span *ngIf="authN.init">init()</span> -->

      <!-- has login with redirect -->
      <!-- <span *ngIf="authN.loginWithRedirect"></span>
          <span *ngIf="authN.loginWithRedirect">loginWithRedirect()</span> -->

      <!-- has login -->
      <!-- <span *ngIf="authN.login"></span>
          <span *ngIf="authN.login">login()</span> -->

      <!-- has register -->
      <!-- <span *ngIf="authN.register"></span>
          <span *ngIf="authN.register">register()</span> -->

      <!-- has logout -->
      <!-- <span *ngIf="authN.logout"></span>
          <span *ngIf="authN.logout">logout()</span> -->

      <!-- claims -->
      <!-- <div *ngIf="(authNSubj | async)?.authN?.claims as claims">
          <hr />
          <span class="property-title">claims:</span>
          <pre><p>{{ claims | json }}</p></pre>
        </div> -->

      <!-- claimsMap -->
      <!-- <div *ngIf="(authNSubj | async)?.authN?.claimsMap as claimsMap">
          <hr />
          <span class="property-title">claims map:</span>
          <pre><p>{{ claimsMap | json}}</p></pre>
        </div> -->
    </div>
  </div>
</mat-card>
