// libs/porrtal/r/shell-blueprint/src/lib/banner/banner.tsx
import { Icon, IconName, Menu, MenuItem } from '@blueprintjs/core';
import { Popover2, Classes } from '@blueprintjs/popover2';
import { BannerProps } from '@porrtal/r-shell';
import { ReactNode } from 'react';
import styles from './banner.module.scss';

export function Banner(props: BannerProps) {
  return (
    <div className={styles['container']}>
      &nbsp;
      {props.bannerData?.displayIcon && (
        <Icon icon={props.bannerData.displayIcon as IconName} />
      )}
      &nbsp;
      <BannerMenu {...props}>
        <h3 className={styles['banner-title']}>
          {props.bannerData?.displayText}
          {props.bannerData?.childData &&
            props.bannerData.childData.length > 0 && <Icon icon="caret-down" />}
        </h3>
      </BannerMenu>
      <span></span>
    </div>
  );
}

function BannerMenu(props: BannerProps & { children: ReactNode | undefined }) {
  if (!props.children || !props.bannerData) {
    return null;
  }

  if (!props.bannerData.childData || props.bannerData.childData.length < 1) {
    return <>props.children</>;
  }

  return (
    <Popover2
      content={
        <Menu className={Classes.POPOVER2_DISMISS}>
          {props.bannerData.childData.map((menuItem) => (
            <MenuItem
              key={menuItem.displayText}
              icon={menuItem.displayIcon as IconName}
              text={
                <>
                  <span>{menuItem.displayText}</span>
                  <Icon
                    className={styles['popout-icon']}
                    icon="document-open"
                    onClick={(evt) => {
                      window.open(menuItem.targetUrl);
                      evt.stopPropagation();
                    }}
                  ></Icon>
                </>
              }
              onClick={(evt) => {
                if (menuItem.targetUrl) {
                  window.location.href = menuItem.targetUrl;
                }
              }}
            />
          ))}
        </Menu>
      }
    >
      {props.children}
    </Popover2>
  );
}

export default Banner;

// libs/porrtal/a/shell-material/src/lib/banner/banner.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { BannerData } from '@porrtal/a-shell';
import { BannerMenuComponent } from '../banner-menu/banner-menu.component';

@Component({
  selector: 'porrtal-banner',
  standalone: true,
  imports: [CommonModule, MatIconModule, BannerMenuComponent],
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BannerComponent implements OnInit {
  @Input()
  public bannerData?: BannerData;

  constructor() {}

  ngOnInit(): void {}
}

<div class="container">
  &nbsp;
  <mat-icon *ngIf="bannerData?.displayIcon">{{
    bannerData?.displayIcon
  }}</mat-icon>
  &nbsp;
  <porrtal-banner-menu
    [bannerData]="bannerData"
    [class]="
      bannerData &&
      bannerData.childData &&
      bannerData.childData.length &&
      bannerData.childData.length > 0
        ? 'banner-with-children'
        : ''
    "
  >
    <h2 class="banner-text">
      {{ bannerData?.displayText }}
      <mat-icon
        class="down-icon"
        *ngIf="
          bannerData &&
          bannerData.childData &&
          bannerData.childData.length &&
          bannerData.childData.length > 0
        "
        >arrow_drop_down</mat-icon
      >
    </h2>
  </porrtal-banner-menu>
  <span></span>
</div>
