// libs/test-comps/second-test-comp/src/lib/test-comps-second-test-comp.tsx
import { Button } from '@blueprintjs/core';
import { EntityMenu } from '@porrtal/r-shell';
import styles from './test-comps-second-test-comp.module.scss';

/* eslint-disable-next-line */
export interface TestCompsSecondTestCompProps {}

export function TestCompsSecondTestComp(props: TestCompsSecondTestCompProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to TestCompsSecondTestComp!</h1>
      <EntityMenu entityType="account" state={{ accountId: 7 }}>
        <Button>Account entity menu</Button>
      </EntityMenu>
      <EntityMenu entityType="appointment" state={{ apptId: 25 }}>
        <Button>Appointment entity menu</Button>
      </EntityMenu>
    </div>
  );
}

export default TestCompsSecondTestComp;

// libs/porrtal-components/a/second-test-comp-lib/src/lib/test-comps-second-test-comp/test-comps-second-test-comp.component.ts
import { ChangeDetectionStrategy, Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ViewState } from '@porrtal/a-api';
import { EntityMenuComponent } from '@porrtal/a-shell-material';

@Component({
  selector: 'porrtal-test-comps-second-test-comp',
  standalone: true,
  imports: [CommonModule, EntityMenuComponent],
  templateUrl: './test-comps-second-test-comp.component.html',
  styleUrls: ['./test-comps-second-test-comp.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TestCompsSecondTestCompComponent {

  @Input() viewState?: ViewState;

  constructor() {}

}

<div class="container">
  <p>test-comps-second-test-comp works!</p>
  <porrtal-entity-menu entityType="account" [state]="{ accountId: 7 }">
    <button>Account entity menu</button>
  </porrtal-entity-menu>
  <porrtal-entity-menu entityType="appointment" [state]="{ appointmentId: 25 }">
    <button>Appointment entity menu</button>
  </porrtal-entity-menu>
</div>
