// libs/porrtal-components/a-first-test-comp-lib/src/lib/test-comps-first-test-comp/test-comps-first-test-comp.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoggerEntry, PaneType, StateObject, ViewState } from '@porrtal/a-api';
import { v4 as uuidv4 } from 'uuid';
import {
  LoggerStateService,
  SearchStateService,
  ShellStateService,
} from '@porrtal/a-shell';
import { Observable } from 'rxjs';

@Component({
  selector: 'porrtal-test-comps-first-test-comp',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './test-comps-first-test-comp.component.html',
  styleUrls: ['./test-comps-first-test-comp.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TestCompsFirstTestCompComponent {
  private _viewState?: ViewState;
  @Input() set viewState(value: ViewState | undefined) {
    this._viewState = value;
  }
  get viewState() {
    return this._viewState;
  }

  public searchText$: Observable<string>;

  public numberStrings = [
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
  ];

  constructor(
    private shellStateService: ShellStateService,
    private searchStateService: SearchStateService,
    private loggerStateService: LoggerStateService
  ) {
    this.searchText$ = searchStateService.select('debouncedSearchText');
  }

  launchAndCloseSearch(info: {
    paneType: PaneType;
    componentName: string;
    componentModule: string;
    displayText: string;
    displayIcon?: string;
    stateV?: StateObject;
    stateVS?: StateObject;
    key?: string;
    lookupModuleFunction?: boolean;
  }) {
    this.createAndLaunchView(info);
    this.searchStateService.dispatch({
      type: 'closeSearchDialog',
    });
  }

  createAndLaunchView(info: {
    paneType: PaneType;
    componentName: string;
    componentModule: string;
    displayText: string;
    displayIcon?: string;
    stateV?: StateObject;
    stateVS?: StateObject;
    key?: string;
    lookupModuleFunction?: boolean;
  }) {
    const viewComponentModules = this.shellStateService.get(
      'viewComponentModules'
    );
    const newViewId = uuidv4();
    this.shellStateService.dispatch({
      type: 'registerView',
      view: {
        viewId: newViewId,
        key: info.key ?? newViewId,
        launchAtStartup: false,
        paneType: info.paneType,
        componentName: info.componentName,
        componentModule: info?.lookupModuleFunction
          ? viewComponentModules[info.componentModule]
          : info.componentModule,
        displayText: info.displayText,
        displayIcon: info.displayIcon,
        state: info.stateV,
      },
    });
    this.shellStateService.dispatch({
      type: 'launchView',
      viewId: newViewId,
      state: info.stateVS,
    });
  }

  createLogEntry(entry: LoggerEntry) {
    this.loggerStateService.dispatch({
      type: 'postEntry',
      entry,
    });
  }
}

<div class="container">
  <h1>Welcome to TestCompsFirstTestCompComponent!</h1>
  <button
    (click)="
      createAndLaunchView({
        paneType: 'right',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'one{a}{b.c}',
        displayIcon: 'home',
        stateV: { a: ' bam!', b: { c: ' bambam!!' } },
        stateVS: { myProp: 'State to be passed to view instance.' }
      })
    "
  >
    launch right
  </button>
  &nbsp;
  <button
    (click)="
      launchAndCloseSearch({
        paneType: 'right',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'one{a}{b.c}',
        displayIcon: 'home',
        stateV: { a: ' bam!', b: { c: ' bambam!!' } }
      })
    "
  >
    launch right and close search
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        paneType: 'bottom',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'one',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch bottom
  </button>
  &nbsp;
  <br />
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'right',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'Seven-First',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch key=7 right
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'bottom',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'Seven-Bottom',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch key=7 bottom
  </button>
  &nbsp;
  <br />
  <p>second component</p>
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'right',
        componentName: 'TestCompsSecondTestCompComponent',
        componentModule: '@porrtal-components/a-second-test-comp-lib',
        displayText: 'Seven-Second',
        displayIcon: 'home',
        stateV: {},
        lookupModuleFunction: true
      })
    "
  >
    launch second key=7 right
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'bottom',
        componentName: 'TestCompsSecondTestCompComponent',
        componentModule: '@porrtal-components/a-second-test-comp-lib',
        displayText: 'Seven-Second',
        displayIcon: 'home',
        stateV: {},
        lookupModuleFunction: true
      })
    "
  >
    launch second key=7 bottom
  </button>
  &nbsp;
  <hr />

  <div>search text: {{ searchText$ | async }}</div>

  <h4>state:</h4>
  <pre [innerHtml]="viewState?.state ?? '(no state)' | json"></pre>

  <div style="margin-top: 10px; margin-bottom: 10px;">
    <porrtal-entity-menu
    entityType="appointment"
    [state]="{ someKey: 'someValue' }"
  >
    <span
      class="link-button"
      style="display: grid; grid-template-columns: 24px auto; cursor: pointer;"
    >
      <mat-icon>account_box</mat-icon>
      <span style="margin-left: 5px">{{ 'appointment entity menu launcher' }}</span>
    </span>
  </porrtal-entity-menu>

  </div>
  <div>
    logger:&nbsp;
    <button
      (click)="
        createLogEntry({
          system: 'porrtal-app',
          subsystem: 'test',
          component: 'test',
          severity: 'info',
          consumer: 'developer',
          message: 'log 1 message',
          messageDetail:
            'this is a longer message to show how a long message looks when displayed in the logger messages component.  Here we need to make it REALLY long to see what happens if there is overflow.  Does it wrap the line?  Or do something else?  \r\n\r\n and what about new lines?',
          isRead: false,
          user: 'datumgeek'
        })
      "
    >
      log1
    </button>
    &nbsp;
    <button
      (click)="
        createLogEntry({
          system: 'porrtal-app',
          subsystem: 'test',
          component: 'test',
          severity: 'info',
          consumer: 'developer',
          message: 'log 2 message',
          messageDetail:
            'this is a longer message to show how a long message looks when displayed in the logger messages component.  Here we need to make it REALLY long to see what happens if there is overflow.  Does it wrap the line?  Or do something else?  \r\n\r\n and what about new lines?',
          isRead: false,
          user: 'datumgeek'
        })
      "
    >
      log2
    </button>
    &nbsp;
    <button
      (click)="
        createLogEntry({
          system: 'porrtal-app',
          subsystem: 'test',
          component: 'test',
          severity: 'info',
          consumer: 'developer',
          message: 'log 3 message',
          messageDetail:
            'this is a longer message to show how a long message looks when displayed in the logger messages component.  Here we need to make it REALLY long to see what happens if there is overflow.  Does it wrap the line?  Or do something else?  \r\n\r\n and what about new lines?',
          isRead: false,
          user: 'datumgeek'
        })
      "
    >
      log3
    </button>
    &nbsp;
  </div>
  <p *ngFor="let item of numberStrings">
    {{ item }}
  </p>
</div>

// libs/porrtal-components/r-first-test-comp-lib/src/lib/test-comps-first-test-comp.tsx
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ViewState } from '@porrtal/r-api';
import {
  useDebouncedSearchText,
  useSearchAction,
  useShellDispatch,
  useLoggerDispatch,
  EntityMenu,
} from '@porrtal/r-shell';
import styles from './test-comps-first-test-comp.module.scss';
import { v4 as uuidv4 } from 'uuid';

export interface TestCompsFirstTestCompProps {
  viewState: ViewState;
}

export function TestCompsFirstTestComp(props: TestCompsFirstTestCompProps) {
  const shellDispatch = useShellDispatch();
  const searchAction = useSearchAction();
  const searchText = useDebouncedSearchText();
  const loggerDispatch = useLoggerDispatch();

  console.log('test comp', props.viewState.key, searchText);

  return (
    <div className={styles['container']}>
      <h1>Welcome to TestCompsFirstTestComp!</h1>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: uuidv4(),
              launchAtStartup: false,
              paneType: 'right',
              componentName: 'TestCompsFirstTestComp',
              componentModule: '@porrtal-components/r-first-test-comp-lib',
              displayText: 'one{a}{b.c}',
              displayIcon: 'home',
              state: { a: ' bam!', b: { c: ' bambam!!' } },
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
            state: { myProp: 'State to be passed to view instance.' },
          });
        }}
      >
        launch right
      </button>
      &nbsp;
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: uuidv4(),
              launchAtStartup: false,
              paneType: 'right',
              componentName: 'TestCompsFirstTestComp',
              componentModule: '@porrtal-components/r-first-test-comp-lib',
              displayText: 'one{a}{b.c}',
              displayIcon: 'home',
              state: { a: ' bam!', b: { c: ' bambam!!' } },
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
          });
          searchAction?.closeSearchDialog();
        }}
      >
        launch right and close search
      </button>
      &nbsp;
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: uuidv4(),
              launchAtStartup: false,
              paneType: 'bottom',
              componentName: 'TestCompsFirstTestComp',
              componentModule: '@porrtal-components/r-first-test-comp-lib',
              displayText: 'one',
              displayIcon: 'home',
              state: {},
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch bottom
      </button>
      &nbsp;
      <br />
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: '7',
              launchAtStartup: false,
              paneType: 'right',
              componentName: 'TestCompsFirstTestComp',
              componentModule: '@porrtal-components/r-first-test-comp-lib',
              displayText: 'Seven-First',
              displayIcon: 'home',
              state: {},
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch key=7 right
      </button>
      &nbsp;
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: '7',
              launchAtStartup: false,
              paneType: 'bottom',
              componentName: 'TestCompsFirstTestComp',
              componentModule: '@porrtal-components/r-first-test-comp-lib',
              displayText: 'Seven-Bottom',
              displayIcon: 'home',
              state: {},
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch key=7 bottom
      </button>
      &nbsp;
      <br />
      <p>second component</p>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: '7',
              launchAtStartup: false,
              paneType: 'right',
              componentName: 'TestCompsSecondTestComp',
              componentModule: '@porrtal-components/r-second-test-comp-lib',
              displayText: 'Seven-Second',
              displayIcon: 'home',
              state: {},
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch second key=7 right
      </button>
      &nbsp;
      <button
        onClick={() => {
          const newViewId = uuidv4();
          shellDispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              key: '7',
              launchAtStartup: false,
              paneType: 'bottom',
              componentName: 'TestCompsSecondTestComp',
              componentModule: '@porrtal-components/r-second-test-comp-lib',
              displayText: 'Seven-Second',
              displayIcon: 'home',
              state: {},
            },
          });
          shellDispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch second key=7 bottom
      </button>
      &nbsp;
      <hr />
      <div>search text: {searchText}</div>
      <div>state: {JSON.stringify(props.viewState?.state)}</div>
      <div style={{ marginTop: '10px', marginBottom: '10px' }}>
        <EntityMenu
          key={`menu-7`}
          entityType="appointment"
          state={{ someKey: 'someValue' }}
        >
          <span style={{ cursor: 'pointer' }}>
            {'appointment entity menu launcher'}
          </span>
        </EntityMenu>
      </div>
      <div>
        logger:&nbsp;
        <button
          onClick={() => {
            const newViewId = uuidv4();
            loggerDispatch({
              type: 'postEntry',
              entry: {
                system: 'porrtal-app',
                subsystem: 'test',
                component: 'test',
                severity: 'info',
                consumer: 'developer',
                message: 'log 1 message',
                messageDetail:
                  'this is a longer message to show how a long message looks when displayed in the logger messages component.  Here we need to make it REALLY long to see what happens if there is overflow.  Does it wrap the line?  Or do something else?  \r\n\r\n and what about new lines?',
                isRead: false,
                user: 'datumgeek',
              },
            });
            shellDispatch({
              type: 'launchView',
              viewId: newViewId,
            });
          }}
        >
          log1
        </button>
        &nbsp;
        <button
          onClick={() => {
            const newViewId = uuidv4();
            loggerDispatch({
              type: 'postEntry',
              entry: {
                system: 'porrtal-app',
                subsystem: 'test',
                component: 'test',
                severity: 'info',
                consumer: 'developer',
                message: 'log 2 message',
                messageDetail:
                  'this is a longer message to show how a long message looks when displayed in the logger messages component...',
                isRead: false,
                user: 'datumgeek',
              },
            });
            shellDispatch({
              type: 'launchView',
              viewId: newViewId,
            });
          }}
        >
          log2
        </button>
        &nbsp;
        <button
          onClick={() => {
            const newViewId = uuidv4();
            loggerDispatch({
              type: 'postEntry',
              entry: {
                system: 'porrtal-app',
                subsystem: 'test',
                component: 'test',
                severity: 'info',
                consumer: 'developer',
                message: 'log 3 message',
                messageDetail:
                  'this is a longer message to show how a long message looks when displayed in the logger messages component...',
                isRead: false,
                user: 'datumgeek',
              },
            });
            shellDispatch({
              type: 'launchView',
              viewId: newViewId,
            });
          }}
        >
          log3
        </button>
        &nbsp;
      </div>
      {['one', 'two', 'three', 'four', 'five', 'six', 'seven'].map((item) => (
        <p key={item}>{item}</p>
      ))}
    </div>
  );
}

export default TestCompsFirstTestComp;
