// libs/porrtal/shell-material/src/lib/view-stack/view-stack.tsx
import { Box, Icon, Tab, Tabs } from '@mui/material';
import React, { useMemo } from 'react';
import { useShellDispatch, ViewHost, ViewStackProps } from '@porrtal/shell';
import styles from './view-stack.module.scss';
import { ContextMenu, NestedMenuItem, IconMenuItem } from 'mui-nested-menu';
import { paneArrangements, PaneType, paneTypes } from '@porrtal/api';

export function ViewStack(props: ViewStackProps) {
  const dispatch = useShellDispatch();
  const currentIndex = useMemo(() => {
    for (let ii = 0; ii < props.pane.viewStates.length; ii++) {
      if (props.pane.viewStates[ii].key === props.pane.currentKey) {
        return ii;
      }
    }
    return -1;
  }, [props.pane]);

  const handleChange = (event: React.SyntheticEvent, newIndex: number) => {
    dispatch({
      type: 'setCurrentViewStateByKey',
      key: props.pane.viewStates[newIndex].key,
      pane: props.pane,
    });
  };

  const moveIcons: { [key in PaneType]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  return (
    <div className={styles['container']}>
      <Box
        sx={{
          borderBottom: 1,
          borderColor: 'divider',
          backgroundColor: 'gainsboro',
        }}
      >
        <Tabs
          value={currentIndex}
          variant="scrollable"
          scrollButtons="auto"
          onChange={handleChange}
          className={styles['tabs']}
        >
          {props.pane.viewStates.map((item, index) => (
            <Tab
              key={item.key}
              icon={
                <Icon style={{ position: 'relative', top: '3px' }}>
                  {item.displayIcon}
                </Icon>
              }
              iconPosition="start"
              label={
                <ContextMenu
                  menuItems={[
                    <NestedMenuItem
                      key={'arrange'}
                      leftIcon={<Icon>pivot_table_chart</Icon>}
                      parentMenuOpen={true}
                      label={'Arrange...'}
                    >
                      {paneArrangements.map((paneArrangement) => (
                        <IconMenuItem
                          key={`arrange-${paneArrangement}`}
                          leftIcon={
                            <Icon className="material-icons-outlined">
                              {props.pane.arrange === paneArrangement
                                ? 'done'
                                : ''}
                            </Icon>
                          }
                          label={`${paneArrangement}`}
                          onClick={() =>
                            dispatch({
                              type: 'arrangePane',
                              pane: props.pane,
                              paneArrangement,
                            })
                          }
                        ></IconMenuItem>
                      ))}
                    </NestedMenuItem>,
                    <NestedMenuItem
                      key={'move'}
                      leftIcon={<Icon>open_with</Icon>}
                      parentMenuOpen={true}
                      label={'Move to...'}
                    >
                      {paneTypes
                        .filter(
                          (paneType) =>
                            paneType !== 'search' &&
                            paneType !== props.pane.paneType
                        )
                        .map((paneType) => (
                          <IconMenuItem
                            key={`move-to-${paneType}`}
                            leftIcon={
                              <Icon className="material-icons-outlined">
                                {moveIcons[paneType]}
                              </Icon>
                            }
                            label={`${paneType} pane`}
                            onClick={() =>
                              dispatch({
                                type: 'moveView',
                                key: item.key,
                                toPane: paneType,
                              })
                            }
                          ></IconMenuItem>
                        ))}
                    </NestedMenuItem>,
                  ]}
                >
                  <span>
                    {item.displayText}&nbsp;
                    <Icon
                      style={{ position: 'relative', top: '5px' }}
                      onClick={(evt) => {
                        dispatch({ type: 'deleteViewState', key: item.key });
                        evt.stopPropagation();
                      }}
                    >
                      clear
                    </Icon>
                  </span>
                </ContextMenu>
              }
            ></Tab>
          ))}
        </Tabs>
      </Box>
      <div className={styles['view-host-container']}>
        {props.pane.viewStates.map((item, index) => (
          <ViewHost
            key={item.key}
            viewState={item}
            zIndex={index === currentIndex ? 10 : 0}
          ></ViewHost>
        ))}
        <div
          style={{
            zIndex: 5,
            backgroundColor: 'white',
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
          }}
        ></div>
      </div>
    </div>
  );
}

export default ViewStack;

// libs/porrtal/a/shell-material/src/lib/view-stack/view-stack.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Pane, paneTypes, paneArrangements, ViewState, PaneType } from '@porrtal/a-api';
import { MatTabsModule } from '@angular/material/tabs';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule, MatMenuTrigger } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { ShellStateService, ViewHostComponent } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-workspace-view-stack',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatIconModule,
    MatMenuModule,
    MatDividerModule,
    ViewHostComponent,
  ],
  templateUrl: './view-stack.component.html',
  styleUrls: ['./view-stack.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ViewStackComponent {
  _pane?: Pane;
  @Input() set pane(value: Pane | undefined) {
    this._pane = value;
    this.paneTypes = paneTypes.filter(
      (pt) => pt !== 'search' && pt !== (this._pane?.paneType ?? '')
    );
  }
  get pane() {
    return this._pane;
  }
  @ViewChild(MatMenuTrigger, { static: true }) matMenuTrigger?: MatMenuTrigger;
  public paneTypes?: string[];
  public paneArrangements = paneArrangements;
  menuTopLeftPosition = { x: '0', y: '0' };
  public moveIcons: { [key: string]: string } = {
    nav: 'arrow_circle_left_outlined',
    main: 'arrow_circle_up_outlined',
    bottom: 'arrow_circle_down_outlined',
    right: 'arrow_circle_right_outlined',
    search: 'clear',
  };

  constructor(private shellStateService: ShellStateService) {}

  doContextMenu(evt: MouseEvent, viewState: ViewState): void {
    evt.preventDefault();
    evt.stopPropagation();

    // we record the mouse position in our object
    this.menuTopLeftPosition.x = evt.clientX + 'px';
    this.menuTopLeftPosition.y = evt.clientY + 'px';

    if (this.matMenuTrigger) {
      this.matMenuTrigger.menuData = { viewState };
      this.matMenuTrigger.openMenu();
    }
  }

  doCloseTab(evt: MouseEvent, viewState: ViewState): void {
    this.shellStateService.dispatch({
      type: 'deleteViewState',
      key: viewState.key,
    });
  }

  doMoveTab(evt: MouseEvent, viewState: ViewState, toPaneType: string): void {
    console.log('do move tab', viewState, toPaneType);
    this.shellStateService.dispatch({
      type: 'moveView',
      key: viewState.key,
      toPane: toPaneType as PaneType,
    });
  }
}

<mat-tab-group preserveContent>
  <mat-tab
    *ngFor="let viewState of pane?.viewStates"
    [label]="viewState.displayText"
  >
    <ng-template mat-tab-label>
      <mat-icon
        (contextmenu)="doContextMenu($event, viewState)"
        class="tab-icon"
        >{{ viewState.displayIcon }}</mat-icon
      >
      <span (contextmenu)="doContextMenu($event, viewState)">{{
        viewState.displayText
      }}</span>
      <mat-icon
        (click)="doCloseTab($event, viewState)"
        inline="true"
        class="close-icon"
        >close</mat-icon
      >
    </ng-template>
    <porrtal-workspace-view-host
      [viewState]="viewState"
    ></porrtal-workspace-view-host>
  </mat-tab>
</mat-tab-group>

<!-- an hidden div is created to set the position of appearance of the menu-->
<div
  style="visibility: hidden; position: fixed"
  [style.left]="menuTopLeftPosition.x"
  [style.top]="menuTopLeftPosition.y"
  [matMenuTriggerFor]="rightMenu"
></div>

<!-- standard material menu -->
<mat-menu #rightMenu="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button mat-menu-item (click)="doCloseTab($event, viewState)">
      <span>
        <mat-icon inline="true" class="menu-close-icon">close</mat-icon>
        <span>Close Tab</span>
      </span>
    </button>
    <mat-divider></mat-divider>
    <button mat-menu-item [matMenuTriggerFor]="arrangeOptions">
      <span>
        <mat-icon inline="true" class="menu-close-icon"
          >pivot_table_chart</mat-icon
        >
        <span>Arrange...</span>
      </span>
    </button>
    <button
      mat-menu-item
      [matMenuTriggerFor]="moveOptions"
      [matMenuTriggerData]="{viewState}"
    >
      <span>
        <mat-icon inline="true" class="menu-close-icon">open_with</mat-icon>
        <span>Move To...</span>
      </span>
    </button>
  </ng-template>
</mat-menu>

<mat-menu #arrangeOptions="matMenu">
  <button mat-menu-item *ngFor="let paneArrangement of paneArrangements">
    <span>
      <mat-icon inline="true" class="menu-close-icon"
        >pivot_table_chart</mat-icon
      >
      <span>{{ paneArrangement }}</span>
    </span>
  </button>
</mat-menu>

<mat-menu #moveOptions="matMenu">
  <ng-template matMenuContent let-viewState="viewState">
    <button
      (click)="doMoveTab($event, viewState, paneType)"
      mat-menu-item
      *ngFor="let paneType of paneTypes"
    >
      <span>
        <mat-icon
          inline="true"
          class="menu-move-to-icon material-icons-outlined"
          >{{ moveIcons[paneType] }}</mat-icon
        >
        <span>{{ paneType }}</span>
      </span>
    </button>
  </ng-template>
</mat-menu>
