// libs/porrtal-components/r-quick-start-demo/src/lib/appointment/appointment-location-map/appointment-location-map.tsx
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './appointment-location-map.module.scss';

/* eslint-disable-next-line */
export interface AppointmentLocationMapProps {}

export function AppointmentLocationMap(props: AppointmentLocationMapProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to AppointmentLocationMap!</h1>
    </div>
  );
}

export default AppointmentLocationMap;

// libs/porrtal-components/a-quick-start-demo/src/lib/appointment/appointment-location-map/appointment-location-map.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-appointment-location-map',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './appointment-location-map.component.html',
  styleUrls: ['./appointment-location-map.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppointmentLocationMapComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>appointment-location-map works!</p>
