// libs/porrtal-components/a-quick-start-demo/src/lib/hierarchy/collapsible-tree/collapsible-tree.component.ts
﻿/*
Copyright 2022 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'porrtal-collapsible-tree',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './collapsible-tree.component.html',
  styleUrls: ['./collapsible-tree.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CollapsibleTreeComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>collapsible-tree works!</p>

// libs/porrtal-components/r-quick-start-demo/src/lib/hierarchy/collapsible-tree/collapsible-tree.tsx
﻿/*
Copyright 2023 Comcast Cable Communications Management, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import styles from './collapsible-tree.module.scss';

/* eslint-disable-next-line */
export interface CollapsibleTreeProps {}

export function CollapsibleTree(props: CollapsibleTreeProps) {
  return (
    <div className={styles['container']}>
      <h1>Welcome to CollapsibleTree!</h1>
    </div>
  );
}

export default CollapsibleTree;
