// libs/porrtal-components/a/first-test-comp-lib/src/lib/test-comps-first-test-comp/test-comps-first-test-comp.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PaneType, StateObject, ViewState } from '@porrtal/a-api';
import { v4 as uuidv4 } from 'uuid';
import { ShellStateService } from '@porrtal/a-shell';

@Component({
  selector: 'porrtal-workspace-test-comps-first-test-comp',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './test-comps-first-test-comp.component.html',
  styleUrls: ['./test-comps-first-test-comp.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TestCompsFirstTestCompComponent {
  private _viewState?: ViewState;
  @Input() set viewState(value: ViewState | undefined) {
    this._viewState = value;
  };
  get viewState() {
    return this._viewState;
  }

  public numberStrings = ['one', 'two', 'three', 'four', 'five', 'six', 'seven'];

  constructor(private shellStateService: ShellStateService) {}

  createAndLaunchView(info: {
    paneType: PaneType,
    componentName: string,
    componentModule: string,
    displayText: string,
    displayIcon?: string,
    stateV?: StateObject,
    stateVS?: StateObject,
    key?: string,
}) {
  const newViewId = uuidv4();
  this.shellStateService.dispatch({
    type: 'registerView',
    view: {
      viewId: newViewId,
      key: info.key ?? newViewId,
      launchAtStartup: false,
      paneType: info.paneType,
      componentName: info.componentName,
      componentModule: info.componentModule,
      displayText: info.displayText,
      displayIcon: info.displayIcon,
      state: info.stateV,
    },
  });
  this.shellStateService.dispatch({
    type: 'launchView',
    viewId: newViewId,
    state: info.stateVS,
  });
}}


<div class="container">
  <h1>Welcome to TestCompsFirstTestCompComponent!</h1>
  <button
    (click)="
      createAndLaunchView({
        paneType: 'right',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'one{a}{b.c}',
        displayIcon: 'home',
        stateV: { a: ' bam!', b: { c: ' bambam!!' } },
        stateVS: { myProp: 'State to be passed to view instance.' }
      })
    "
  >
    launch right
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        paneType: 'right',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'one{a}{b.c}',
        displayIcon: 'home',
        stateV: { a: ' bam!', b: { c: ' bambam!!' } }
      })
    "
  >
    launch right and close search
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        paneType: 'bottom',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'one',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch bottom
  </button>
  &nbsp;
  <br />
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'right',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'Seven-First',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch key=7 right
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'bottom',
        componentName: 'TestCompsFirstTestCompComponent',
        componentModule: '@porrtal-components/a-first-test-comp-lib',
        displayText: 'Seven-Bottom',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch key=7 bottom
  </button>
  &nbsp;
  <br />
  <p>second component</p>
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'right',
        componentName: 'TestCompsSecondTestCompComponent',
        componentModule: '@porrtal-components/a-second-test-comp-lib',
        displayText: 'Seven-Second',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch second key=7 right
  </button>
  &nbsp;
  <button
    (click)="
      createAndLaunchView({
        key: '7',
        paneType: 'bottom',
        componentName: 'TestCompsSecondTestCompComponent',
        componentModule: '@porrtal-components/a-second-test-comp-lib',
        displayText: 'Seven-Second',
        displayIcon: 'home',
        stateV: {}
      })
    "
  >
    launch second key=7 bottom
  </button>
  &nbsp;
  <hr />

  <!-- <div>search text: {{searchText}}</div> -->

  <h4>state:</h4>
  <pre [innerHtml]="viewState?.state ?? '(no state)' | json"></pre>

  <div>
    logger:&nbsp;
    <button>log1</button>
    &nbsp;
    <button>log2</button>
    &nbsp;
    <button>log3</button>
    &nbsp;
  </div>
  <p *ngFor="let item of numberStrings">
    {{ item }}
  </p>
</div>

// libs/test-comps/first-test-comp/src/lib/test-comps-first-test-comp.tsx
import { ViewState } from '@porrtal/api';
import {
  useDebouncedSearchText,
  useSearchAction,
  useShellDispatch,
} from '@porrtal/shell';
import styles from './test-comps-first-test-comp.module.scss';
import { v4 as uuidv4 } from 'uuid';

export interface TestCompsFirstTestCompProps {
  viewState: ViewState;
}

export function TestCompsFirstTestComp(props: TestCompsFirstTestCompProps) {
  const dispatch = useShellDispatch();
  const searchAction = useSearchAction();
  const searchText = useDebouncedSearchText();
  console.log('test comp', props.viewState.key, searchText);

  return (
    <div className={styles['container']}>
      <h1>Welcome to TestCompsFirstTestComp!</h1>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: uuidv4(),
              launchAtStartup: false,
              paneType: 'right',
              componentName: '@test-comps/first-test-comp',
              displayTextTemplate: 'one{a}{b.c}',
              displayIconTemplate: 'home',
              state: { a: ' bam!', b: { c: ' bambam!!' } },
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch right
      </button>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: uuidv4(),
              launchAtStartup: false,
              paneType: 'right',
              componentName: '@test-comps/first-test-comp',
              displayTextTemplate: 'one{a}{b.c}',
              displayIconTemplate: 'home',
              state: { a: ' bam!', b: { c: ' bambam!!' } },
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
          searchAction?.closeSearchDialog();
        }}
      >
        launch right and close search
      </button>

      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: uuidv4(),
              launchAtStartup: false,
              paneType: 'bottom',
              componentName: '@test-comps/first-test-comp',
              displayTextTemplate: 'one',
              displayIconTemplate: 'home',
              state: {},
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch bottom
      </button>
      <br />
      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: '7',
              launchAtStartup: false,
              paneType: 'right',
              componentName: '@test-comps/first-test-comp',
              displayTextTemplate: 'Seven-First',
              displayIconTemplate: 'home',
              state: {},
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch key=7 right
      </button>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: '7',
              launchAtStartup: false,
              paneType: 'bottom',
              componentName: '@test-comps/first-test-comp',
              displayTextTemplate: 'Seven-Bottom',
              displayIconTemplate: 'home',
              state: {},
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch key=7 bottom
      </button>
      <br />
      <p>second component</p>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: '7',
              launchAtStartup: false,
              paneType: 'right',
              componentName: '@test-comps/second-test-comp',
              displayTextTemplate: 'Seven-Second',
              displayIconTemplate: 'home',
              state: {},
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch second key=7 right
      </button>
      <button
        onClick={() => {
          const newViewId = uuidv4();
          dispatch({
            type: 'registerView',
            view: {
              viewId: newViewId,
              keyTemplate: '7',
              launchAtStartup: false,
              paneType: 'bottom',
              componentName: '@test-comps/second-test-comp',
              displayTextTemplate: 'Seven-Second',
              displayIconTemplate: 'home',
              state: {},
            },
          });
          dispatch({
            type: 'launchView',
            viewId: newViewId,
          });
        }}
      >
        launch second key=7 bottom
      </button>
      <hr />
      <div>search text: {searchText}</div>

      {[
        'one',
        'two',
        'three',
        'four',
        'five',
        'six',
        'seven',
        'eight',
        'nine',
        'ten',
      ].map((item) => (
        <p key={item}>{item}</p>
      ))}
    </div>
  );
}

export default TestCompsFirstTestComp;
