// libs/porrtal-components/a-quick-start-demo/src/lib/account/account-search/account-search.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ViewState } from '@porrtal/a-api';
import { map, Observable } from 'rxjs';
import { Account, accountData } from '../../data/account-data';
import { SearchStateService } from '@porrtal/a-shell';
import * as Moment from 'moment';
import { EntityMenuComponent } from '@porrtal/a-shell-material';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'porrtal-account-search',
  standalone: true,
  imports: [CommonModule, MatIconModule, EntityMenuComponent],
  templateUrl: './account-search.component.html',
  styleUrls: ['./account-search.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccountSearchComponent {
  @Input() viewState?: ViewState;

  public filteredAccounts$?: Observable<Account[]>;
  public searchText$?: Observable<string>;
  public Moment = Moment;

  constructor(private searchStateService: SearchStateService) {
    this.searchText$ = searchStateService.select('debouncedSearchText');

    this.filteredAccounts$ = searchStateService
      .select('debouncedSearchText')
      .pipe(
        map((searchText) =>
          accountData.filter((account) => {
            return (
              JSON.stringify(account)
                .toLowerCase()
                .indexOf(searchText.toLowerCase()) >= 0
            );
          })
        )
      );
  }

  public formatAmount(amount: number) {
    return '$' + amount.toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,');
  }
}

<div class="container">
  <h3 class="title">Account Search: {{ searchText$ | async }}</h3>
  <div class="data-container">
    <ng-container *ngIf="filteredAccounts$ | async as accounts">
      <ng-container *ngFor="let account of accounts">
        <porrtal-entity-menu
          entityType="account"
          [state]="{ accountId: account.accountId }"
        >
          <span
            class="link-button"
            style="display: grid; grid-template-columns: 24px auto"
          >
            <mat-icon>account_box</mat-icon>
            <span style="margin-left: 5px">{{ account.name }}</span>
          </span>
        </porrtal-entity-menu>
        <div class="orders-data-container">
          <ng-container *ngFor="let order of account.orders">
            <span>{{ order.item }}</span>
            <span>{{ formatAmount(order.amount) }}</span>
            <span>{{ Moment(order.date).format('YYYY-DD-MM') }}</span>
          </ng-container>
        </div>
      </ng-container>
    </ng-container>
  </div>
</div>

// libs/porrtal-components/r-quick-start-blueprint/src/lib/account/account-search/account-search.tsx
import { useDebouncedSearchText } from '@porrtal/r-shell';
import { ViewComponentProps } from '@porrtal/r-api';
import { accountData } from '../../data/account-data';
import styles from './account-search.module.scss';
import Moment from 'moment';
import { Fragment } from 'react';

export function AccountSearch(props: ViewComponentProps) {
  const searchText = useDebouncedSearchText();
  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>Account Search: {searchText}</h3>
      <div className={styles['data-container']}>
        {accountData
          .filter((account) => {
            return (
              JSON.stringify(account)
                .toLowerCase()
                .indexOf(searchText.toLowerCase()) >= 0
            );
          })
          .map((account) => (
            <Fragment key={account.accountId}>
              <div>{account.name}</div>
              <div className={styles['orders-data-container']}>
                {account?.orders.map((order) => (
                  <>
                    <span>{order.item}</span>
                    <span>
                      {'$' +
                        order.amount
                          .toFixed(0)
                          .replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')}
                    </span>
                    <span>{Moment(order.date).format('YYYY-DD-MM')}</span>
                  </>
                ))}
              </div>
            </Fragment>
          ))}
      </div>
    </div>
  );
}

export default AccountSearch;
