// libs/porrtal-components/quick-start-demo/src/lib/account/account-nav/account-nav.tsx
import { Icon } from '@blueprintjs/core';
import { EntityMenu, useShellDispatch } from '@porrtal/shell';
import { useEffect, useState } from 'react';
import { AccountData, fetchAccountData } from '../../data/account-data';
import styles from './account-nav.module.scss';

/* eslint-disable-next-line */
export interface AccountNavProps {}

export function AccountNav(props: AccountNavProps) {
  const [accountData, setAccountData] = useState<AccountData>();
  useEffect(() => {
    fetchAccountData(500).then((d) => setAccountData(d));
  }, []);
  const shellDispatch = useShellDispatch();
  return (
    <div className={styles['container']}>
      <h3 className={styles['title']}>Top Three Accounts</h3>
      <div className={styles['data-container']}>
        {accountData &&
          accountData
            .map((account) => {
              const total = account?.orders.reduce((accumulator, order) => {
                return accumulator + order.amount;
              }, 0);
              return {
                ...account,
                total,
              };
            })
            .sort((a, b) => b.total - a.total)
            .filter((acct, ii) => ii < 3)
            .map((acct) => {
              return (
                <>
                  <EntityMenu key={`menu-${acct.accountId}`} entityType="account" state={{accountId: acct.accountId}}>
                    <p className={styles['link-button']}>
                      <Icon icon="mugshot" />
                      <span style={{ marginLeft: '5px' }}>{acct.name}</span>
                    </p>
                  </EntityMenu>
                  <p key={`total-${acct.accountId}`}>{'$' + acct.total.toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')}</p>
                </>
              );
            })}
        {!accountData && <div>loading data...</div>}
      </div>
    </div>
  );
}

export default AccountNav;

// libs/porrtal-components/a/quick-start-demo/src/lib/account/account-nav/account-nav.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EntityMenuComponent } from '@porrtal/a-shell-material';
import {
  Account,
  accountData,
  fetchAccountData,
} from '../../data/account-data';
import { MatIconModule } from '@angular/material/icon';
import { ViewState } from '@porrtal/a-api';

@Component({
  selector: 'porrtal-account-nav',
  standalone: true,
  imports: [CommonModule, MatIconModule, EntityMenuComponent],
  templateUrl: './account-nav.component.html',
  styleUrls: ['./account-nav.component.scss'],
})
export class AccountNavComponent {
  @Input() viewState?: ViewState;

  public topThreeAccounts: (Account & { total: number })[] = [];
  constructor() {
    this.topThreeAccounts = [
      ...accountData
        .map((account) => {
          const total = account.orders.reduce((accumulator, order) => {
            return accumulator + order.amount;
          }, 0);
          return {
            ...account,
            total,
          };
        })
        .sort((a, b) => b.total - a.total)
        .filter((acct, ii) => ii < 3),
    ];

    console.log('top three accounts', this.topThreeAccounts);
  }
}

<div class="container">
  <h3 class="title">Top Three Accounts</h3>
  <div class="data-container">
    <ng-container *ngFor="let account of topThreeAccounts">
      <porrtal-entity-menu
        entityType="account"
        [state]="{ accountId: account.accountId }"
      >
        <span class="link-button" style="display: grid; grid-template-columns: 24px auto;">
          <mat-icon>account_box</mat-icon>
          <span style="margin-left: 5px">{{ account.name }}</span>
        </span>
      </porrtal-entity-menu>
      <span>
        $
        {{
          account.total
            | number
              : '1.0-0' //.toFixed(0).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')
        }}
      </span>
    </ng-container>
  </div>
</div>
